### ISSUE TITLE
Implement PubID parsing for ISO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#1]
Document identifier parsing is currently implemented in https://github.com/relaton/relaton-iso

ISO document identifiers look like this:

International standards:
* "ISO 9001" (undated identifier)
* "ISO 9001:2015" (dated identifier)
* "ISO/{WD, CD, DIS, FDIS} 9001:2015" (identifier for draft document)

Technical report ("TR") or Technical specification ("TS"):
* "ISO/TR 9001" (undated identifier)
* "ISO/TR 9001:2015" (dated identifier)
* "ISO/TR {WD, CD, DIS, FDIS} 9001:2015" (identifier for draft document)

ISO/IEC co-published international standards:
* "ISO/IEC 27001" (undated)
* "ISO/IEC 27001:2013" (dated)
* "ISO/IEC TR 27001:2013"

ISO Amendments:
* "ISO 8601:2019/Amd 1" (undated) 
* "ISO 8601:2019/Amd 1:2022" (dated)
* "ISO 8601:2019/DAmd 1" (DIS stage)
* "ISO 8601:2019/FDAmd 1" (FDIS stage)

There is another issue that contains the full description but I have to find it.

**Comment by ronaldtse** [comment]
@mico can you help implement this gem like the nist-pubid? This would be a lot easier. You can find specs and parsing code in relaton-iso. Thanks!

**Comment by ronaldtse** [comment]
Here's the full list of deliverables original from https://github.com/relaton/relaton-iso/issues/9

These types are officially defined here: https://www.iso.org/deliverables-all.html.

Technical Specification
* type: `technicalSpecification`
* title: `{publisher}/TS XXXXX`
* example: https://www.iso.org/standard/70292.html ("ISO/IEC TS 29125:2017")

Technical Report
* type: `technicalReport`
* title: `{publisher}/TR XXXXX`
* example: https://www.iso.org/standard/72437.html ("ISO/IEC TR 27103:2018")

Publicly available specification
* type: `publiclyAvailableSpecification`
* title: `{publisher}/PAS XXXXX`
* example: https://www.iso.org/standard/42141.html ("ISO/PAS 28002:2010")

Standard
* type:`internationalStandard`
* title: `{publisher} XXXXX`
* example: https://www.iso.org/standard/66435.html ("ISO/IEC 27000:2018")

Guide
* type: `guide`
* title: `{publisher} Guide XXX`
* example: https://www.iso.org/standard/44651.html ("ISO Guide 73:2009")

IWA
* type: `internationalWorkshopAgreement`
* title: `{publisher}/IWA XXXX`
* example: https://www.iso.org/standard/63027.html ("IWA 12:2013")

**Comment by mico** [comment]
@ronaldtse what data I can use to test the parser? Using Algolia I can only find data for identifiers, but how can I get identifiers list?

**Comment by ronaldtse** [comment]
@mico this is a bulk list of 8282 identifiers to try with. I believe ISO has ~25,000 standards in total. Let's use this list.

[iso-sample-identifiers.txt](https://github.com/metanorma/pubid-iso/files/8151040/iso-sample-identifiers.txt)

**Comment by mico** [comment]
> @mico this is a bulk list of 8282 identifiers to try with. I believe ISO has ~25,000 standards in total. Let's use this list.
> 
> [iso-sample-identifiers.txt](https://github.com/metanorma/pubid-iso/files/8151040/iso-sample-identifiers.txt)

There is identifiers like:
FprISO 8437-2
FprISO 22125-2
FprISO/IEC 17029

What is "Fpr" there? Should I just ignore them?

**Comment by ronaldtse** [comment]
"Fpr" stands for "Final ProoF", which is a "stage code" like "WD", "DIS" etc, but it is appended to the front.. we need to implement this pattern.

**Comment by mico** [comment]
@ronaldtse what use cases for this parser? We were using "nist-pubid" for old -> new PubID conversion and to get document URL. I believe here we want to get document URL at least.

**Comment by ronaldtse** [comment]
The goal is to move the URN functionality from Relaton-ISO into here. And we will go back to refactor Relaton-ISO to use this gem.

**Comment by ronaldtse** [comment]
Please also help document the individual elements of the document ID scheme so we have a full explanation of how the scheme works. 

The URN scheme is documented at RFC 5141.

**Comment by mico** [comment]
> The goal is to move the URN functionality from Relaton-ISO into here. And we will go back to refactor Relaton-ISO to use this gem.
Could you give an example of URN functionality in Relaton-ISO?

**Comment by ronaldtse** [comment]
https://github.com/relaton/relaton-iso/issues/85

You can see https://github.com/relaton/relaton-iso#search-for-standards-using-keywords

**Comment by ronaldtse** [comment]
@mico I found several errors in the original txt, here's the fixed one.
[iso-sample-identifiers-v2.txt.zip](https://github.com/metanorma/pubid-iso/files/8153926/iso-sample-identifiers-v2.txt.zip)

**Comment by ronaldtse** [comment]
metanorma-iso: https://github.com/metanorma/metanorma-iso/blob/568c109c71a07707101a7410770a2213765332a9/lib/isodoc/iso/metadata.rb#L17-L28

relaton-iso:
https://github.com/relaton/relaton-iso/blob/1e8fa72f3ff79ca2972e01518fbb9d87b1afed22/lib/relaton_iso/scrapper.rb#L13-L49

https://github.com/relaton/relaton-iso/blob/528597f13bab5a9c09955dcc50bab97246949931/lib/relaton_iso/iso_bibliography.rb#L134-L142

These are the ISO doctypes:
https://github.com/metanorma/metanorma-iso/blob/568c109c71a07707101a7410770a2213765332a9/lib/metanorma/iso/validate.rb#L90-L94

There is the "IWA {NN}" pattern for international workshop agreements, too.

**Comment by mico** [comment]
Seems "relaton-iso" create wrong URN's for some identifiers, for example it provides URN `"urn:iso:std:iso-tr:tr:30406:stage-60.60:ed-1:en,fr"` for PubID `"ISO/TR 30406:2017"`
Where "iso-tr" at "originator" place, but in rfc5141:
`originator    = "iso" / "iso-iec" / "iso-cie" / "iso-astm" / "iso-ieee" / "iec"`
So I believe it should be: `"urn:iso:std:iso:tr:30406:stage-60.60:ed-1:en,fr"`
@ronaldtse could you confirm?

**Comment by ronaldtse** [comment]
Yes indeed it was incorrect. That's why we need proper parsing.

**Comment by mico** [comment]
@ronaldtse could you help with this one: https://www.iso.org/standard/54944.html
It's "IWA 8:2009". In RFC "IWA" is the type:
`
      iwa   = International Workshop Agreement
`
But here it's using like an organization. Is it wrong identifier? Should be "ISO IWA 8:2009" ?

**Comment by ronaldtse** [comment]
@mico the IWA is a special case. It is a "joint publication from many organizations/people" so treat IWA as the publisher. It is just "IWA 8:2009" not "ISO IWA 8:2009".

**Comment by mico** [comment]
> "Fpr" stands for "Final ProoF", which is a "stage code" like "WD", "DIS" etc, but it is appended to the front. We need to implement this pattern.

@ronaldtse I didn't find documents with "Fpr" prefix on iso.org, is it the same as "PRF" stage? Should we support this identifiers?

**Comment by mico** [comment]
identifiers with "ED" on the list "iso-sample-identifiers-v2.txt":
```
ISO/IEC 30142 ED1
ISO 22610:2006 Ed
ISO 17121:2000 Ed 1
ISO 14442:2006 Ed 2
ISO 11553-1 Ed.2
ISO 9652-4:2000 Ed 1
ISO 16622:2002 Ed 1
ISO 16001:2008 Ed 1
ISO 293:2004 Ed 3
```

Should I just drop "ed" part here or should I parse it as edition? On iso.org I can't find documents using this ids, need to drop "ed" part. Only these 9 documents have "ed" part.

**Comment by mico** [comment]
Found few document with document number with "."
First idea was it's edition number because ISO 11243 have edition 3 document, but ISO 21143 don't have edition 2, so now I'm confused what to do with this numbers...
ISO 11243.3
ISO/FDIS 21420.2
ISO 21143.2

**Comment by ronaldtse** [comment]
> I didn't find documents with "Fpr" prefix on iso.org, is it the same as "PRF" stage? Should we support this identifiers?

We should support parsing of these identifiers, but not the generation of them. We should use the "PRF" stage when we generate the PubID.

> Should I just drop "ed" part here or should I parse it as edition? On iso.org I can't find documents using this ids, need to drop "ed" part. Only these 9 documents have "ed" part.

This is tricky because the "edition number" and "edition year" cannot be found together in an official PubID. The URN does require the edition number not the edition year.

1. When we parse "ISO 16622:2002 Ed 1" ("Ed 1", "ED1", "Ed.1"), we need to store both information in the class, and when we convert it into URN the URN will be correct.
2. When we generate a PubID, we do not use the "Ed 1" information.

> Found few document with document number with "."
> First idea was it's edition number because ISO 11243 have edition 3 document, but ISO 21143 don't have edition 2, so now I'm confused what to do with this numbers...

These indicate the "iteration" of ballot (number of ballots that have occurred at the same stage). For example, an FDIS ballot failed, and a second FDIS ballot ("FDIS2 21420" or "FDIS 21420.2") is held. This is the ID that identifies that document being balloted.

There are 2 patterns:
* `{stage}{iteration} {docnumber}`
* `{stage} {docnumber}.{iteration}`

e.g.
https://www.iso.org/standard/80136.html
<img width="894" alt="Screenshot 2022-03-03 at 8 54 04 AM" src="https://user-images.githubusercontent.com/11865/156475162-eb4bf4c4-322a-4f8e-a0df-702779c37937.png">

https://www.iso.org/obp/ui/#iso:std:iso:14100:dis:ed-1:v1:en
<img width="931" alt="Screenshot 2022-03-03 at 8 55 14 AM" src="https://user-images.githubusercontent.com/11865/156475333-6c6da3dc-67e3-4349-a3fd-556c2b4deddc.png">

**Comment by ronaldtse** [comment]
We also need to parse the "amendments" and "corrigendum" PubIDs. An additional list is provided here.
[iso-sample-identifiers-additional.txt.zip](https://github.com/metanorma/pubid-iso/files/8174002/iso-sample-identifiers-additional.txt.zip)

**Comment by mico** [comment]
> * When generating the PubID, we should generate the second pattern.

So after parsing PubID I should be able to generate PubID (it can look different from original) and URN, right?

**Comment by mico** [comment]
> These indicate the "iteration" of ballot (number of ballots that have occurred at the same stage). For example, an FDIS ballot failed, and a second FDIS ballot ("FDIS2 21420" or "FDIS 21420.2") is held. This is the ID that identifies that document being balloted.

Do we represent ballot "iteration" in URN?

**Comment by ronaldtse** [comment]
Yes, iteration is placed under Stage in RFC 5141. 

```
urn:iso:std:iso:128:-71:cancelled:ed-1:en
      urn:iso:std:iso:128:-71:stage-30.98.v2:ed-1:en
      both refer to the cancelled (30.98 = project deleted) 1st edition
      of ISO 128-71, in English; the second example refers specifically
      to the 2nd iteration (projectversion) at stage 30
```

**Comment by mico** [comment]
There is identifier on the list: "ISO 10438-1:2003 EN 80601-2-60", seems it's 2 identifiers:
ISO 10438-1:2003 and IEC 80601-2-60
Makes me think we shouldn't adapt our parser to everything on the list. Sometimes there are some mistakes.

**Comment by ronaldtse** [comment]
@mico yes, this "ISO 10438-1:2003 EN 80601-2-60" is a mistake". It should have only been "ISO 10438-1:2003".

> Makes me think we shouldn't adapt our parser to everything on the list. Sometimes there are some mistakes.

Just let me know when you find exceptions, I will let you know whether it is a mistake. Thanks.

**Comment by ronaldtse** [comment]
This is done in #2
