### ISSUE TITLE
(URGENT) Document type appears after "ISO" with slash unless there are copublishers 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#105]
Correct behavior:

* If there are copublishers, copublishers are separated by slashes, and the document type appears after the copublishers and a space. (e.g. "ISO/IEC WD 27001")
* If there are no copublishers, the document type is placed after a slash after "ISO". (e.g. "ISO/WD 123")

`ISO WD 1000-1.3`

> We are not delimiting ISO from status with a slash.

This is wrong. It should have been "ISO/WD 1000-1.3".

`ISO/IEC/IEEE TR 1000-1-1:2001`
> 
> * We are not delimiting publishers from document type with a slash.

This is correct. The previous `ISO/IEC/IEEE/TR` pattern is wrong.

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-iso/issues/102#issuecomment-1251774037_

**Comment by mico** [comment]
@opoudjis could you help to reproduce this bug?
We already have a test for that case: https://github.com/metanorma/pubid-iso/blob/main/spec/pubid_iso/identifier_spec.rb#L767
but it didn't fail.

**Comment by ronaldtse** [comment]
This is fixed in #115.
