### ISSUE TITLE
Default publisher must always be ISO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#109]
```ruby
Pubid::Iso::Identifier.new(number: 1000).to_s
=> " 1000"
```

This output should be "ISO 1000".

All PubID gems must have default publishers.

**Comment by mico** [comment]
@ronaldtse are you using old gem? This was fixed a long time ago.
https://github.com/metanorma/pubid-iso/blob/main/lib/pubid/iso/identifier.rb#L30

**Comment by ronaldtse** [comment]
Wow, I was using pubid-iso 0.1.10, because Metanorma has locked the version. I've tried it on the latest 0.1.12 and it works. Closing.
