### ISSUE TITLE
Issues with the latest pubid-iso

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#117]
The relaton-iso has issues with the latest pubis-iso v0.1.12
https://github.com/relaton/relaton-iso/actions/runs/3122107588/jobs/5063838020#step:6:302

Two tests fail because identical amendments comparation is false in https://github.com/relaton/relaton-iso/blob/73e86fe8e156b26fd9dac59a21ae37971ca17c31/lib/relaton_iso/iso_bibliography.rb#L245

One test fails because the pubid-iso raises the `Pubid::Iso::Errors::SupplementWithoutYearError`

**Comment by mico** [comment]
@andrew2net do you want me to update relaton-iso to fix the errors related to latest pubid-iso update?
Shall we have a task in relaton-iso project for this instead of having it here?

**Comment by ronaldtse** [comment]
@mico would you be able to help fix this in relaton-iso? @andrew2net is on holiday this week. Thanks!

**Comment by andrew2net** [comment]
@mico no, this issue can't be fixed in the relaton-iso. Previous version of the pubis-iso works correctly, the latest version doesn't work as expected.
Comparation of 2 equivalent amendments returns false in the latest version of pubis-iso.
It also fails with `Pubid::Iso::Errors::SupplementWithoutYearError` when the [document](https://www.iso.org/standard/85632.html) without year in amendment is fetched.
Please run the latest of relaton-iso tests with new pubis-iso before releasing.
