### ISSUE TITLE
Render `iteration` in ISO URN

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#119]
Moreover, there are "iteration" with the same format:
>    iteration     = "v" DIGITS

We should handle iterations in ISO URNs as per RFC 5141.

_Originally posted by @mico in https://github.com/metanorma/pubid-iso/issues/24#issuecomment-1257473737_

**Comment by mico** [comment]
@ronaldtse we are already rendering interations in URN but only for identifiers with stage defined:
```
      let(:pubid) { "ISO/FDIS 21420.2" }
      let(:urn) { "urn:iso:std:iso:21420:stage-50.00.v2" }
```

and ignoring stage when it's not defined:
```
      let(:pubid) { "ISO 21143.2" }
      let(:urn) { "urn:iso:std:iso:21143" }
```

I cannot find any references why did we implement this behaviour. Do you have any ideas?
