### ISSUE TITLE
Handle IWA identifiers (and its draft stages)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#12]
We need to handle the IWA draft stages.

```
AWI IWA 36
AWI IWA 39
AWI IWA 41
AWI IWA 42
CD IWA 37
CD IWA 37-1
CD IWA 37-2
CD IWA 37-3
CD IWA 40
CD IWA 42
ISO/IWA 32:2019(en)
ISO/WD IWA 19
IWA 14-1:2013
IWA 19:2017
IWA 2 N3
IWA 24:2016
IWA 26:2017
IWA 31:2020
IWA 32:2019
IWA 34:2021
IWA 34:2021(en)
IWA 35:2020
IWA 37-1:2022
IWA 37-2:2022
IWA 37-3:2022
IWA 40:2022(en)
IWA 42
IWA 8:2009
NP IWA 30-2
NP IWA 32
NP IWA 33
PRF IWA 36
PRF IWA 37-1
PRF IWA 37-3
PRF IWA 40
PRF IWA 42
WD IWA 19
```

We need to parse items like:
```
ISO/IWA 32:2019(en)
ISO/WD IWA 19
```

But the correct forms are:
```
IWA 32:2019(en)
WD IWA 19
```

(Updated list)

**Comment by ronaldtse** [comment]
I've committed the above samples:
https://github.com/metanorma/pubid-iso/blob/7702bab1d42305660706887419bf26f84d5a5242/spec/fixtures/iwa-pubid.txt#L1-L17

**Comment by mico** [comment]
Does AWI == NP stage? How should I convert it to URN and PubID?

**Comment by ronaldtse** [comment]
@mico AWI is not NP stage. AWI = "Approved Work Item". NP = "New Work Item Proposal".

https://www.metanorma.org/author/iso/ref/document-attributes/#document-type-and-stage

<img width="610" alt="Screenshot 2022-03-09 at 2 17 17 AM" src="https://user-images.githubusercontent.com/11865/157300527-e0b1639e-f0a0-4de9-ba30-e0f23e33b774.png">

**Comment by mico** [comment]
> @mico AWI is not NP stage. AWI = "Approved Work Item". NP = "New Work Item Proposal".
> 
> https://www.metanorma.org/author/iso/ref/document-attributes/#document-type-and-stage

How can I know is it stage 10.99 or 10.98?

These identifiers are at stage 20.00:
https://www.iso.org/standard/61118.html
https://www.iso.org/standard/50073.html
https://www.iso.org/standard/79649.html
Is AWI stage or copublisher here?

**Comment by ronaldtse** [comment]
@mico AWI is stage.

> These identifiers are at stage 20.00:

Good find... then we need to update that AWI is 20.00... 

Ping @opoudjis for comment.

**Comment by opoudjis** [comment]
I'll need to review the ISO documentation.

**Comment by ronaldtse** [comment]
@mico just use AWI as 20.00. No need to wait for @opoudjis , there is no ISO documentation on the stage codes mapping to document stages.

**Comment by ronaldtse** [comment]
This is actually not completed at all! What was handled in #21 is "AWI" (Approved Work Item). Not "IWA". Reopening.
