### ISSUE TITLE
Stage names

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#128]
We are outputting stage names in bibdata, and ideally I would like a function to output stage names for identifiers (`typed_stage_name`), as well as stage abbreviations. However, this is not high priority, given how long this has already taken.

**Comment by opoudjis** [comment]
What I need is a value for ext/stagename. I have never used it, but @Intelligent2013 does:

https://github.com/metanorma/metanorma-iso/issues/342

It is intended I assume for the front cover. Until now, I have been populating it with (2), the generic stage name. I assume it should be typed in this instance too, but that is a question @Intelligent2013 will have a better sense of than me.

**Comment by ronaldtse** [comment]
So you need (3), not (2) i.e. 
> 3. the ISO deliverable stage abbreviation, i.e. Any document at stage 30 will be called a "Committee draft".

The place it is used is here:
<img width="626" alt="Screen Shot 2022-10-05 at 1 03 33 PM" src="https://user-images.githubusercontent.com/11865/193985175-171966b1-c586-43f1-8c3a-6556da4cbb16.png">

Notice that the strings for (3) is different from the abbreviated typed_stage_abbrev:
* PWI: "Preliminary Work Item"
* AWI: "Approved Work Item"
* WD: "Working Draft"
* CD: "Committee Draft"
* DIS: "Draft" (instead of "Draft International Standard")
* FDIS: "Final Draft" (instead of "Final Draft International Standard")

**Comment by Intelligent2013** [comment]
Currently in ISO XSLT, the stage name determines in this priority (from high to low):
- `iso-standard/bibdata/status/stage[@language = <current document language>]`
Presentation XML instance:
```xml
<status>
	<stage abbreviation="IS" language="">60</stage>
	<stage abbreviation="IS" language="en">International Standard</stage>
	<substage>60</substage>
</status>
```
In this example, the stage name will be `International Standard`.
This case added in the ticket https://github.com/metanorma/mn-native-pdf/issues/345 specially for multi-language support.

- if the value `iso-standard/bibdata/status/stage[@language = <current document language>]` is empty, then `iso-standard/bibdata/ext/stagename`
(Actually this case is from previous version of XSLT, and didn't removed for back compatibility for old XMLs. I don't sure this case is working now, and may be removed... May be this is a workaround solution for case when `iso-standard/bibdata/status/stage[@language = <current document language>]` is empty actually)


Regarding:

> > 3. the ISO deliverable stage abbreviation, i.e. Any document at stage 30 will be called a "Committee draft".

> The place it is used is here:
> <img width="626" alt="Screen Shot 2022-10-05 at 1 03 33 PM" src="https://user-images.githubusercontent.com/11865/193985175-171966b1-c586-43f1-8c3a-6556da4cbb16.png">

> Notice that the strings for (3) is different from the abbreviated typed_stage_abbrev:
> ...
> * FDIS: "Final Draft" (instead of "Final Draft International Standard")

In ISO XSLT the label `Final Draft` is a special case for stage abbreviations `FDIS`, `FDAmd` and `FDAM`:
```
<xsl:when test="$stage-abbreviation = 'FDIS' or $stage-abbreviation = 'FDAmd' or $stage-abbreviation = 'FDAM'">FINAL DRAFT</xsl:when>
```
In the current presentation XML (for instance, rice-en.fdis.presentation.xml) there is `ext/stagename` with this value:
```xml
  <ext>
     ...
    <stagename>Final draft</stagename>
  </ext>
</bibdata>
```
It seems I have to update ISO XSLT in this place.

The main confusing I think that in some case we need render stage name together with 'International Standard', like this:
![image](https://user-images.githubusercontent.com/5559926/194031078-8db23ac7-d8a0-4d29-9ac4-1525b9bc5412.png)

and in another cases need render them separately:
![image](https://user-images.githubusercontent.com/5559926/194031153-65c45786-2600-4174-975b-07a7df98a972.png)
