### ISSUE TITLE
Conclusion from ISO: "FDAmd" vs "FDAM", "FDAM" is the only correct abbreviation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#132]
It's now official from ISO:
* FDAmd, DAmd, CD Amd are all incorrect -- these appear due to a database/implementation limitation on the ISO content system.

The correct identifiers as per Directives Part 1 are:
* FDAM, DAM, CDAM
* (I can't find CDAM in DP1 though)

From ISO/CS:
> The presentation is a database vs Directives thing. We’re actually trying to get the internal database to display DAM, FDAM, CDAM, as these are the correct identifiers.
> ... not sure why they started as DAmd in our database and remain that way; it’s probably a banal operational/technical limitation/historical reason that’s persisted. What shows on the website is drawn from our projects database. DAM, FDAM, CDAM are correct, as stated in DP1.

I'm still asking about CORs, i.e. "CD Cor" vs "CDCOR", so hold off until we get information on that.

**Comment by mico** [comment]
@ronaldtse oops, does it mean we might need to get rid of "short" vs "long" PubID rendering?

**Comment by ronaldtse** [comment]
@mico yes, we should only do the "short" version from now on. Let's remove the "long" version. At least ISO/CS *finally* admitted this is their mistake! 😉

**Comment by ronaldtse** [comment]
This has been implemented.
