### ISSUE TITLE
typed_stage_name is not defensive

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#135]
This method is currently implemented as:

````
"#{stage.short_name} #{TYPE_NAME[type.to_sym]}"
````

`type` can be nil if not set explicitly, which makes this method crash. Moreover, `TYPE_NAME` is only defined for three types to begin with.

If the type is not set explicitly for an identifier, you must set it to the default value of "International Standard"; so

````ruby
def type
  super || "IS"
end
````

````
Pubid::Iso::Identifier.new(number: 200, stage: "PRF").typed_stage_name
````

This should not be crashing.

````
Pubid::Iso::Identifier.new(number: 200, stage: "PRF", type: "DIR").typed_stage_name
````

This should be returning _Proof of a Directive_.

Assume that I am going to call your methods with anything.

**Comment by opoudjis** [comment]
````ruby
      def metadata_stagename(node)
        id = iso_id_default(iso_id_params(node))
        if @amd
          id.amendments&.first&.stage&.name ||
            id.corrigendums&.first&.stage&.name
        else
          begin
            id.typed_stage_name
          rescue StandardError
            id.stage&.name
          end
        end
      end
````

This what I'm currently having to do to use the typed_stage_name method.

I trust you can see that I should not be having to do this.

**Comment by opoudjis** [comment]
I was putting the ordinal of iteration into the stage name ("First Working Draft")

The experience of this gem development makes me extremely reluctant to suggest this, especially as internationalisation would be called for; but if you wanted to do so,

````ruby
require "twitter_cldr"

....
ret =  {stage name}
if iteration && %w(20 30).include?(stage)
          prefix = iteration.to_i.localize(@lang.to_sym)
            .to_rbnf_s("SpelloutRules", "spellout-ordinal")
          ret = "#{prefix.capitalize} #{ret.downcase}"
        end
````

**Comment by ronaldtse** [comment]
> This what I'm currently having to do to use the typed_stage_name method.
> I trust you can see that I should not be having to do this.

Correctness of the `typed_stage_name` aside, if pubid-iso returns you with an error, you should report to the user that the PubID is invalid.

I do agree that the `typed_stage_name` should be defensive.

However, I also have to say that the "stage" is optional, because:
```
Pubid::Iso::Identifier.new(number: 200, stage: "PRF")
```
Is an UNDATED pubid. There cannot be a stage for it.

I'm not sure if we're handling this properly. Maybe we should have a method `dated_pubid?` to determine that?

**Comment by opoudjis** [comment]
> Correctness of the typed_stage_name aside, if pubid-iso returns you with an error, you should report to the user that the PubID is invalid.

I will, when the gem covers all reasonable scenarios. Right now it doesn't.
