### ISSUE TITLE
Languages duplication in URN

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#141]
The latest version of the gem doubles languages in URN
```
> Pubid::Iso::Identifier.parse("ISO 19115:2003(en,fr)").urn
=> "urn:iso:std:iso:19115:en,fr:en,fr"
```

**Comment by ronaldtse** [comment]
This is a bug indeed, thanks @andrew2net !

**Comment by mico** [comment]
@andrew2net I didn't manage to reproduce the bug, but I add a test with your case.

**Comment by andrew2net** [comment]
@mico I think you tested with the GitHub version, not the released gem. Please try to switch to the `v0.2.1` tag with `git checkout v0.2.1` and run the test case.

**Comment by mico** [comment]
@andrew2net please try `pubid-iso` 0.2.2

**Comment by andrew2net** [comment]
@mico it's getting worse. First I got this:
```
     NoMethodError:
       undefined method `urn_stage=' for #<Pubid::Iso::Identifier:0x00007f7a9d4c6868 @publisher="ISO", @number="19115"@4, @part="1", @year=2014, @edition="1">
       Did you mean?  stage=
```
Please increase the minor version of a gem if you change a public method name or make any other updates that change the usage of a gem.

After fixing the method's name I got:
```
    NoMethodError:
       undefined method `abbr' for 90.93:Float
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:66:in `render_stage'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:36:in `block in prerender_params'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `each'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `map'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `prerender_params'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:20:in `prerender'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:17:in `prerender'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:26:in `render_base_identifier'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:79:in `render'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:24:in `render'
     # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/identifier.rb:211:in `to_s'
```

**Comment by mico** [comment]
> @mico it's getting worse. First I got this:
> 
> ```
>      NoMethodError:
>        undefined method `urn_stage=' for #<Pubid::Iso::Identifier:0x00007f7a9d4c6868 @publisher="ISO", @number="19115"@4, @part="1", @year=2014, @edition="1">
>        Did you mean?  stage=
> ```
> 
> Please increase the minor version of a gem if you change a public method name or make any other updates that change the usage of a gem.
> 
> After fixing the method's name I got:
> 
> ```
>     NoMethodError:
>        undefined method `abbr' for 90.93:Float
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:66:in `render_stage'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:36:in `block in prerender_params'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `each'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `map'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:33:in `prerender_params'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:20:in `prerender'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:17:in `prerender'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:26:in `render_base_identifier'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-core-1.2.2/lib/pubid/core/renderer/base.rb:79:in `render'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/renderer/base.rb:24:in `render'
>      # /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.2.2/lib/pubid/iso/identifier.rb:211:in `to_s'
> ```

Are you going to fix it?
If you want me to fix it, please add details on how to reproduce the error.

**Comment by andrew2net** [comment]
> Are you going to fix it?
> If you want me to fix it, please add details on how to reproduce the error.

@mico I've made a new issue https://github.com/metanorma/pubid-iso/issues/145
