### ISSUE TITLE
Undefined method `urn_stage='

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#145]
@mico there was a method `urn_stage=` which we used to handle the [International harmonized stage codes](https://www.iso.org/stage-codes.html). After updating pubid to the last version the method disappears.
```
> pubid = Pubid::Iso::Identifier.parse_from_title("ISO 19115-1:2014 Geographic information \u2014 Metadata \u2014 Part 1: Fundamentals")
#<Pubid::Iso::Identifier:0x00007ff14d167678 @publisher="ISO", @number="19115"@4, @part="1", @year=2014>
> pubid.urn_stage = 90.93
undefined method `urn_stage=' for #<Pubid::Iso::Identifier:0x00007ff14d167678 @publisher="ISO", @number="19115"@4, @part="1", @year=2014>
Did you mean?  stage=
```
As I understand the `stage` attribute is not the same as the `urn_stage`. How do we suppose to handle the stage codes?

**Comment by mico** [comment]
@andrew2net you can add harmonized_code to the stage, there are the example in test cases:
https://github.com/metanorma/pubid-iso/blob/fd279ee6d8afe54c81699356d65d4f4f57860fdb/spec/pubid_iso/identifier/create_new_identifier_spec.rb#L78

I'll add documentation on it after finish "typed stage" implementation, it again could change API.
