### ISSUE TITLE
Harmonized stage codes for Stages and Typed Stages

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#148]
I'm trying to figure out what codes to use for Stages and Typed Stages.
As I understand if it's just a Stage (not a Typed Stage) then for every identifier Type Harmonized stage codes will be the same, right?
Example:
"WD TR", "WD TS", "WD PAS" will have Harmonized stage codes "20.20 20.60 20.99". right?
Is it the same for "WD Amd", "WD Cor"?

For "DTS", "DTR", "DIS", "DPAS" seems it's also the same (40.00 40.20 40.60 40.92 40.93 50.00 50.20 50.60 50.92), am I right?
Are "DCOR" and "DAMD" also have the same Harmonized stage codes as "DTS", "DTR" and "DIS"?

I didn't manage to find codes for FDIS.
@ronaldtse could you help me find all the codes for all stages and typed stages? (maybe point me to where to look)

**Comment by ronaldtse** [comment]
See https://www.metanorma.org/author/iso/ref/document-attributes/ for most of the stage codes and abbreviations.

**Comment by ronaldtse** [comment]
I've elaborated out the typed stages for you:
[20221031-iso-typed-stages.xlsx](https://github.com/metanorma/pubid-iso/files/9902206/20221031-iso-typed-stages.xlsx)

**Comment by ronaldtse** [comment]
Please proceed with this list. I have sent a separate email to ISO/CS publishing to confirm the list of codes.

**Comment by ronaldtse** [comment]
This has been implemented in the multiple PRs.
