### ISSUE TITLE
Iteration in URN stages

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#149]
In [RFC5141](https://www.rfc-editor.org/rfc/rfc5141.html) I found reference to stage iterations:

> urn:iso:std:iso:128:-71:stage-30.98.v2:ed-1:en
>       both refer to the cancelled (30.98 = project deleted) 1st edition
>       of ISO 128-71, in English; the second example refers specifically
>       to the 2nd iteration (projectversion) at stage 30
> 

But we don't use iterations for URN stages yet. Should we implement it? How do we determine stage iteration?
How does it reflect in PubID?

**Comment by ronaldtse** [comment]
This is like ISO CD 1234.2 (the 2 is the iteration). In a published document, the "iteration number" does not appear in the pubid.

**Comment by mico** [comment]
@ronaldtse seems it's implemented already:
https://github.com/metanorma/pubid-iso/blob/46516de6756d8bb198e26f41b5e301d2db93c688/spec/pubid_iso/identifier_parsing_spec.rb#L109-L115
