### ISSUE TITLE
(URGENT) Incorrect inclusion of /IS in identifier

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#151]
relaton uses pubid-iso. As a result, `relaton fetch "ISO 125"` is returning the identifier of ISO 125 as ISO/IS 125:2020

/IS as a stage must NEVER be output in this context. The stage abbreviation for 60.60 exists, but it must be suppressed from inclusion in document identifiers. This is breaking live usage of relaton, and must be fixed IMMEDIATELY: documents being generated in Metanorma are currently citing documents with incorrect identifiers as a result of this issue.

**Comment by ronaldtse** [comment]
This happens when there is a stage set. This is clearly a bug:

```ruby
irb(main):009:0> Pubid::Iso::Identifier.new(publisher: :ISO, number: 125, stage: "60.60").to_s
=> "ISO/ 125"
```

**Comment by ronaldtse** [comment]
Another issue that is shown by this example is that "ISO 125" does not exist -- what does exist is "ISO/R 125".

pubid-iso needs to handle the "R" document type.

**Comment by ronaldtse** [comment]
> ```ruby
> irb(main):009:0> Pubid::Iso::Identifier.new(publisher: :ISO, number: 125, stage: "60.60").to_s
> => "ISO/ 125"
> ```

Please make sure this is added to the specs.
