### ISSUE TITLE
Create separate Identifier classes for each document type, move TypedStage definitions 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#152]
As per https://github.com/metanorma/pubid-iso/pull/134#discussion_r997664855 , we should move the TypedStage definitions inside:
* `Identifier::InternationalStandard`
* `Identifier::TechnicalReport`
* etc.

So that it is easier to manage future changes of these identifiers.

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-iso/issues/140#issuecomment-1281862878_

**Comment by mico** [comment]
@ronaldtse should "amendments" and "corrigendums" become `Identifier::Amendment` and `Identifier::Corrigendum` instead of being just `Identifier` as well?

**Comment by ronaldtse** [comment]
@mico yes, these type types should be separate Identifier classes.

**Comment by ronaldtse** [comment]
I think both types should be supported.

**Comment by opoudjis** [comment]
Unless this is documented in the Readme page, it is unusable by me. The rspec examples, astonishingly, continue not to provide usage examples that I can copy of how to use the gem.
