### ISSUE TITLE
Parse old style ISO Recommendation Addendums

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#182]
```
ISO/R 91-1970 — Addendum 1
ISO/R 91:1970/Add 1:1975
ISO/R 91:1970/ADD 1:1975
ISO/R 194:1969/Add 4
ISO/R 298:1963/Add 1
ISO/R 947:1969/Add 1:1969
```

**Comment by mico** [comment]
> ISO/R 91-1970 — Addendum 1

@ronaldtse This identifier using em dash "—" instead of hyphen "-". Should I parse this kind of identifiers using em dash?

**Comment by ronaldtse** [comment]
The ‘em-dash’ is often used to separate the
