### ISSUE TITLE
Add example of using Identifier.create to create supplements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#188]
As title:

```
Identifier.create(number: 200, amendments: [{:number=>"1", stage: Pubid::Iso::Stage.new(abbr: :CD, harmonized_code: "30.20")}])
```

_Originally posted by @mico in https://github.com/metanorma/pubid-iso/issues/129#issuecomment-1373251122_

**Comment by mico** [comment]
@ronaldtse it's here already https://github.com/metanorma/pubid-iso#amendment-and-corrigendum

**Comment by ronaldtse** [comment]
Closing.
