### ISSUE TITLE
Pubid::Iso fails to parse Add identifiers

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#206]
Pubid::Iso fails to parse identifiers like these:
[ISO 1942:1983/Add 1:1983/Add 6:1985](https://www.iso.org/standard/6644.html)
[ISO 1942:1983/Add 1:1983](https://www.iso.org/standard/6639.html)
[ISO 1942:1983/Add 1:1983/Add 3:1983](https://www.iso.org/standard/6641.html)
[ISO 1942:1983/Add 1:1983/Add 2:1983](https://www.iso.org/standard/6640.html)
[ISO 1942:1983/Add 1:1983/Add 5:1985](https://www.iso.org/standard/6643.html)
[ISO 1942:1983/Add 1:1983/Add 4:1984](https://www.iso.org/standard/6642.html)
[ISO 5742:1982/Add 1:1985](https://www.iso.org/standard/11853.html)
[ISO/TR 8373:1988/Add 1:1990](https://www.iso.org/standard/15533.html)

_Originally posted by @andrew2net in https://github.com/relaton/relaton-iso/issues/144#issuecomment-1411286100_

**Comment by ronaldtse** [comment]
Thank you @andrew2net for raising this! These pubids are notable and we need to support them. 

@mico can you help here? Thanks.

**Comment by mico** [comment]
> Thank you @andrew2net for raising this! These pubids are notable and we need to support them.
> 
> @mico can you help here? Thanks.

> [ISO 1942:1983/Add 1:1983/Add 6:1985](https://www.iso.org/standard/6644.html)

@ronaldtse Is it an addendum on top of another addendum, or just 2 addendums applied to the same base identifier? (we have these two approaches for supplements too)

**Comment by ronaldtse** [comment]
"ISO 1942:1983/Add 1:1983/Add 6:1985" appears to be the 6th addendum on Addendum 1. Here, "ISO 1942:1983/Add 1:1983" is the base identifier.

**Comment by ronaldtse** [comment]
However this is strange because there is no "ISO 1942:1983/Add 1:1983/Add 1". Let me ask ISO and find out whether these are mistakes.

**Comment by ronaldtse** [comment]
@mico for now please help handle these first:

```
ISO 5742:1982/Add 1:1985
ISO/TR 8373:1988/Add 1:1990
```

**Comment by ronaldtse** [comment]
Since #208 addresses the issue, except the strange identifiers, I will move the remaining to a new issue.
