### ISSUE TITLE
Parse Draft Addenda "ISO/DIS 1151-1/DAD 1"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#210]
DAD is the "Draft Addenda".

https://www.iso.org/obp/ui/#iso:std:iso:1151:-1:ed-4:v1:en
<img width="877" alt="Screen Shot 2023-02-02 at 2 27 36 PM" src="https://user-images.githubusercontent.com/11865/216248432-0691fb9e-7fb1-4ed4-a76f-94efb87410c3.png">

https://www.iso.org/obp/ui/fr/#iso:std:iso:2553:ed-3:v1:en

<img width="592" alt="Screen Shot 2023-02-02 at 2 28 19 PM" src="https://user-images.githubusercontent.com/11865/216248549-93007b98-5e70-4eb8-b149-8e256c320d8f.png">

```
ISO/DIS 1151-1/DAD 1
ISO/DIS 1151-1/DAD 2
ISO 2553/DAD 1:1987
ISO 2631/DAD 1
ISO 3891/DAD 1
ISO 7498/DAD 1
ISO/DIS 8348/DAD 2
ISO 8802/DAD 2
ISO 9595/DAD 1
ISO 9595/DAD 2
ISO 8878/DAD 2 
ISO/DIS 3691/DAD 1 
```

**Comment by mico** [comment]
@ronaldtse Should it work the same way as amendment and corrigendum?

**Comment by ronaldtse** [comment]
@mico this is the "Addenda" which is in the same category as "Amendment" and "Corrigendum".

The stage is just "Draft", which is part of the old ISO process (like DP). The "DAD" is like "DAM" (one stage prior to published AMD).
