### ISSUE TITLE
lightly gem issues with Ruby 2.7

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#231]
As you can see on 

https://github.com/metanorma/metanorma-cli/actions/runs/5052752207/jobs/9066717975

the lightly gem needs to be constrained to version 0.3.2 if it is running under Ruby 2.7; template processing jobs are otherwise failing to install. 

````
ERROR:  Error installing metanorma-cli:
	The last version of lightly (>= 0) to support your Ruby & RubyGems was 0.3.3. Try installing it with `gem install lightly -v 0.3.3` and then running the current command again
	lightly requires Ruby version >= 3.0. The current ruby version is 2.7.8.225.
````

That means your gemspec for the impacted three gems, pubid-iso, pubid-ieee, pubid-bsi, need to include conditional code that looks like

````
  if RUBY_VERSION <= '2.7'
  spec.add_dependency "lightly", "~> 0.3.3"
  else
  spec.add_dependency "lightly", "~> 0.4.0"
  end
````

**Comment by mico** [comment]
@opoudjis why tests for `pubid-nist` and other gems are not falling?

https://github.com/metanorma/pubid-nist/actions/runs/4742992448/jobs/8421981898
