### ISSUE TITLE
Render edition version for URN identifiers

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#24]
> Amendment without year has number "1" before version. Edition has a version (ed-2:v1).

Yes we should do this.

RFC 5141 also has version for edition:
```
   o  Docversion handling:

      urn:iso:std:iso:9999:-1:ed-1:v2:en
      refers to the corrected English version of the 1st edition of ISO
      9999-1

      urn:iso:std:iso:9999:-1:ed-1:v1-amd1:en
      refers to the version comprising the 1st edition of ISO 9999-1,
      incorporating the latest version of Amendment 1, in English

      urn:iso:std:iso:9999:-1:ed-1:v1:en,fr:amd:1:v2:en
      refers to the 2nd version of Amendment 1, in English, which amends
      the 1st version of edition 1 of ISO 9999-1, in English/French
      (bilingual document)

      urn:iso:std:iso:9999:-1:ed-1:v1-amd1.v1:en,fr:amd:2:v2:en
      (isoversion scheme)
      refers to the corrected version of Amendment 2, in English, which
      amends the document comprising the 1st version of edition 1 of ISO
      9999-1 incorporating the 1st version of Amendment 1, in English/
      French (bilingual document)

      urn:iso:std:iso:5817:ed-2:v2:en:cor:1:en
      refers to the 1st version of Technical Corrigendum 1, in English,
      which amends the corrected version of edition 2 of ISO 5817, in
      English

```

It describes `docversion`:

```
   docversion    = "v" (simpleversion / isoversion)

   simpleversion = DIGITS

      <docversion> designates the version number of a document's
      <edition>.  It is altered by correction (corrected version;
      Technical Corrigendum) or amendment (Amendment; Addendum) and is
      distinct from a revision, which changes the edition number.

      In the <simpleversion>, the first version published is 1, and each
      subsequent correction or amendment increases the version number by
      1.

      If no <docversion> is specified, the reference is to the highest
      version number available for the denoted <edition>.

      Current values of <simpleversion>:

         1 - first version published

         2 - corrected version published

   isoversion    = baseversion *includedsuppl

   baseversion   = DIGITS
```
_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-iso/issues/7#issuecomment-1061463317_

**Comment by mico** [comment]
@ronaldtse could you find any PubID examples with corrected edition?
Like "urn:iso:std:iso:9999:-1:ed-1:v2:en" from examples in RFC 5141
I didn't find any, so maybe they are not exist, only in URN form...

**Comment by mico** [comment]
@ronaldtse is this issue about rendering edition as "ed-1"? If yes, we can consider this as closed.
You mentioned "docversion" here, as I understand the format "v{number}", but still doubts what we should consider as "docversion".

Moreover, there are "iteration" with the same format:
>    iteration     = "v" DIGITS

We don't use "v{number}" for base document URN (as docversion or iteration), only as part of amendment or corrigendum. And I feel we are missing something.
I believe we should apply it at least as an iteration.

What do you think?

**Comment by ronaldtse** [comment]
@mico actually maybe we should just drop `docversion` because it is too complicated -- we cannot know this information except from ISO's internal database, e.g. what document has been "corrected" vs what has not been.

We should just deal with `iteration`. But that should be a separate ticket.
