### ISSUE TITLE
URGENT! PRF stage isn't rendered

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#257]
```ruby
Pubid::Iso::Identifier.parse('ISO 7029:2017/PRF Amd 1').to_s
=> "ISO 7029:2017/Amd 1"
```

**Comment by mico** [comment]
> ```ruby
> Pubid::Iso::Identifier.parse('ISO 7029:2017/PRF Amd 1').to_s
> => "ISO 7029:2017/Amd 1"
> ```

"PRF" stage is not rendered by default, see https://github.com/metanorma/pubid-iso/issues/106

**Comment by andrew2net** [comment]
> "PRF" stage is not rendered by default, see #106

@mico what is the way to render `PRF`?

BTW it seems the [examples](https://github.com/metanorma/pubid-iso#using-format-options) in the doc are incorrect. The `pubid.to_s(:ref_num_short)` doesn't work. Shouldn't it be `pubid.to_s(format: :ref_num_short)`?

**Comment by ronaldtse** [comment]
I think it's `pubid.to_s(with_prf: true)`?

**Comment by andrew2net** [comment]
> I think it's `pubid.to_s(with_prf: true)`?

@ronaldtse there is no such option. @mico explain how to render "PRF" please

**Comment by mico** [comment]
> > I think it's `pubid.to_s(with_prf: true)`?
> 
> @ronaldtse there is no such option. @mico explain how to render "PRF" please

@andrew2net 
https://github.com/metanorma/pubid-iso/blob/ed3c5674ba757d0d296df487ba856b86f7c029ec/spec/pubid_iso/identifier/create_new_identifier_spec.rb#L120-L124

**Comment by andrew2net** [comment]
@mico why it doesn't work for me?
```ruby
> Pubid::Iso::Identifier.parse('ISO 7029:2017/PRF Amd 1').to_s with_prf: true
 => "ISO 7029:2017/Amd 1"
```
I use supplement-empty-publisher branch.

**Comment by ronaldtse** [comment]
Is it because Supplements don't support PRF yet?
