### ISSUE TITLE
Create integration tests with relaton-iso

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#260]
We need to be sure that patch version doesn't break Relaton. So we need to create GHA that tests this gem with relaton-iso before release.

**Comment by mico** [comment]
@CAMOBAP can we test `relaton-iso` gem before releasing patch? For minor release, we don't need to do this.

**Comment by CAMOBAP** [comment]
@mico @andrew2net 

1. where this integrated test must be implemented on `pubid-iso`side or `relaton-iso` side? or maybe both?
2. should we implement this approach for other `pubid-*` and/or `relaton-*` gems too?

**Comment by andrew2net** [comment]
@CAMOBAP 
1. The test must be implemented on pubid-iso side. We need to be sure that any new pubid-iso patch version won't break Relaton.
2. Yes, later we will need to implement this approach for all other pubid-*. At this moment Relaton uses only pubid-iso, so we need to start with it.

The pubid-core has similar [dependent-test](https://github.com/metanorma/pubid-core/blob/main/.github/workflows/dependent-tests.yml) already. I think there is a chance that pubid-core pass the dependent-tests with pubid-* gems but the Relaton may have issue. So we need to test pubid-core with Relaton too.

**Comment by CAMOBAP** [comment]
Merged
