### ISSUE TITLE
Identifiers with Edition number only

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#274]
There are two identifiers that have only edition number without year:
- `ISO 11553-1 Ed.2`
- `ISO/IEC 30142 ED1`

(_these identifiers are not available in `relaton-iso-data`, I'm not sure where they come from_)

Should we leave them as it is or maybe we should raise an error when edition number provided without year?

And some identifiers that don't have edition year for supplement, but have edition number (maybe this is another case): 
- `ISO/IEC 10646:2020/CD Amd 1 ED6`
- `ISO/IEC 14496-30:2018/FDAmd 1 ED2`
- `ISO 10791-6:2014/PWI Amd 1 ED1`
- `ISO 11137-2:2013/FDAmd 1 ED3`
- `ISO/IEC 10646-1:1993/pDCOR.2 ED1`
- `ISO/IEC 14496-12:2012/PDAM 4 ED4`

original source of these identifiers: https://github.com/metanorma/pubid-iso/issues/1#issuecomment-1053930136

some of these identifiers mentioned here: https://github.com/metanorma/pubid-iso/issues/102#issuecomment-1251131247

@ronaldtse here https://github.com/metanorma/pubid-iso/issues/1#issuecomment-1057553289 you are saying we don't need to render edition number, only year, this is implemented, but when using "with_edition" option we still getting "Ed" in pubid output (`ISO 11553-1 Ed.2` -> `ISO 11553-1 ED2`)

**Comment by opoudjis** [comment]
@andrew2net Just in case, do you know the provenance of ISO 11553-1 Ed.2? @ronaldtse Has ISO changed editorial practice, so that we need to support both formats?

**Comment by andrew2net** [comment]
@opoudjis I don't. The ISO website doesn't have any ID with edition number.

**Comment by ronaldtse** [comment]
> Should we leave them as it is or maybe we should raise an error when edition number provided without year?

No error should be raised. Closing ticket. Thanks.

> do you know the provenance of ISO 11553-1 Ed.2?

These identifiers are all from iso.org. Some of the funny ones come from older standards' bibliography.
