### ISSUE TITLE
Add documentation on how to use gem and how PubID works

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#37]
* Basic pattern of ISO PubID
* Explain the elements: originator, copublishers, document types, stages, standard number (and part number)
* Dated vs undated PubID
* PubID with language code or not. 2 types of language codes (single letter vs 3166).
* 3 languages of PubID (English, French, Russian)
* URN according to RFC 5141

**Comment by mico** [comment]
@ronaldtse Is it all just about ISO PubID format (that what I understand from description) or about application gem to create new identifiers with different elements and rendering options?

> URN according to RFC 5141

That clearly seems about the format only.

**Comment by ronaldtse** [comment]
It's just about documentation of this gem. We need to write some tutorial / guidance to explain to the potential user what is a pubid, what is the ISO pattern, what are the elements, etc.
