### ISSUE TITLE
Extract Committee Document Identifiers (N-documents) into a separate Identifier subclass

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#47]
Perhaps we should parse N-documents separately from the standard deliverables like IS, TS, TR, etc. Can we have a different class for them?

The types of standard deliverables are the ones we usually parse. Thanks.

e.g.
```ruby
Pubid::Iso.parse("ISO/TC 184/SC 4 N1000").class
# => Pubid::Iso::Identifier::CommitteeDocument
Pubid::Iso.parse("ISO 10001").class
# => Pubid::Iso::Identifier::Deliverable
Pubid::Iso.parse("ISO 10001").kind
# => :international_standard
```

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-iso/issues/46#issuecomment-1128471522_

**Comment by mico** [comment]
There are separate class for TC documents: https://github.com/metanorma/pubid-iso/blob/main/lib/pubid/iso/identifier/technical_committee.rb
@ronaldtse Do you think it is enough?

**Comment by ronaldtse** [comment]
@mico yes it is sufficient to have a separate identifier class now. Can you illustrate how the above pseudocode would look like in the current implementation? Thanks.

**Comment by mico** [comment]
> @mico yes it is sufficient to have a separate identifier class now. Can you illustrate how the above pseudocode would look like in the current implementation? Thanks.

```ruby
Pubid::Iso::Identifier.parse("ISO/TC 184/SC 4 N1000").class
# => Pubid::Iso::Identifier::TechnicalCommittee
Pubid::Iso::Identifier.parse("ISO/TC 184/SC 4 N1000").type
# => {:key=>:tc, :title=>"Technical Committee"}
Pubid::Iso::Identifier.parse("ISO 10001").class
# => Pubid::Iso::Identifier::InternationalStandard
Pubid::Iso::Identifier.parse("ISO 10001").type
# => {:key=>:is, :title=>"International Standard"}
```

**Comment by ronaldtse** [comment]
Thanks @mico, can you help add that to the README? Then we can close this.
