### ISSUE TITLE
Provide letter stage code mapping/linking to/from stage numbers (and URN stages)

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#48]
I found a problem with pubid-iso, I can't update stage using number for Pubid::Iso::Identifier.
```
pubid = Pubid::Iso::Identifier.parse("ISO/IEC 17025:2005")
pubid.stage = "50.00"
```

`pubid.to_s` will return error because it's expecting one of stages abbreviation (like FDIS or CD)

It's ok, until I want to generate URN with stage number like "90.93", with current implementation it's impossible.

**Comment by mico** [comment]
I already started new implementation and faced some challenges.
For example original identifier "ISO/PRF 105-A03" will be converted "ISO/FDIS 105-A03" because they use the same numeric value "50".
Now I use this mapping:
```
    STAGES = { PWI: 0,
               NP: 10,
               AWI: 20,
               WD: 20.20,
               CD: 30,
               DIS: 40,
               FDIS: 50,
               PRF: 50,
               IS: 60 }.freeze
```

**Comment by ronaldtse** [comment]
@mico I believe PRF is at stage 60.00, IS is stage 60.60:
https://www.metanorma.org/author/iso/ref/document-attributes/

**Comment by mico** [comment]
> @mico I believe PRF is at stage 60.00, IS is stage 60.60:
> https://www.metanorma.org/author/iso/ref/document-attributes/

We was discussing before, not all stages at this document are correct. Check here: https://github.com/metanorma/pubid-iso/issues/36

**Comment by ronaldtse** [comment]
Ah right. In this case, we should standardize the stage code from PRF.

There are two different issues:
1. Stage code => Abbreviated stage. This is uncertain for 50.00 and 50.20, as both can be FDIS or PRF.
2. Abbreviated stage => Stage code. This we can set a standard for. We can say that PRF always translates to 60.00, because that's what a "proof" means. FDIS always maps to "50".

> And maybe updating abbreviated stage should not affect numeric value and user should provide both numeric and abbr. values for PubID and URN.

Yes. If the user can provide the stage codes, the update to abbreviated stage should not affect the numeric values (stage codes). The URN should be built from the provided stage codes. The stage codes can be provided by user or by setting the abbreviated stage name.

**Comment by opoudjis** [comment]
There is a clear mapping of numeric stages to abbreviations implemented in https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/front_id.rb

My intent is to replace that code with this gem. If this gem does not support that existing mapping, then I will not be doing so.

ISO may well have committed an act of mind-boggling idiocy, and made PRF ambiguous. But if you're forcing *me* to do the lookup between stage numbers and abbreviation, why should I use this gem at all?

No, that is unreasonable.

If you are provided only with urn stage codes, I expect you to perform the conversion to abbreviations, which is what I am doing now:

````
      STAGE_ABBRS = {
        "00": "PWI",
        "10": "NP",
        "20": "WD",
        "30": "CD",
        "40": "DIS",
        "50": "FDIS",
        "60": "IS",
        "90": "(Review)",
        "95": "(Withdrawal)",
      }.freeze

      def stage_abbr(stage, substage, doctype)
        return nil if stage.to_i > 60

        ret = STAGE_ABBRS[stage.to_sym]
        ret = "PRF" if stage == "60" && substage == "00"
        ret = "AWI" if stage == "10" && substage == "99"
        ret = "AWI" if stage == "20" && substage == "00"
        if %w(amendment technical-corrigendum technical-report
              technical-specification).include?(doctype)
          ret = "D" if stage == "40" && doctype == "amendment"
          ret = "FD" if stage == "50" && %w(amendment technical-corrigendum)
            .include?(doctype)
        end
        ret
      end
````

This code needs to be incorporated into this gem.

**Comment by ronaldtse** [comment]
The stage code implementation in this gem has received proper review by ISO/CS and is correct. I’ve already had an argument with key ISO staff over this issue and they will not change. This gem’s implementation is fully accurate.

**Comment by ronaldtse** [comment]
I’ll check the provided implementation to see what we can incorporate.

**Comment by ronaldtse** [comment]
@opoudjis there is also the “DPAS” prefix that the posted code doesn’t support.

**Comment by opoudjis** [comment]
Given that the code as it stands round trips "ISO/FDTR 6709-1:2008" to "ISO/TR/FDIS 6709-1:2008", no, @ronaldtse, the gem's implementation is not fully accurate. The gem may be accurate in *parsing* ids, but I cannot currently use it to *generate* ids.

Pubid::Iso::Identifier.parse("ISO/FDTR 6709-1:2008").to_s = "ISO/TR/FDIS 6709-1:2008"

**Comment by ronaldtse** [comment]
Indeed this ID is wrong.

**Comment by ronaldtse** [comment]
@mico the behavior right now is incorrect:

```ruby
irb(main):012:0> x = Pubid::Iso::Identifier.new(publisher: "ISO",number: "8601", part: "1",year: 2019)
=> #<Pubid::Iso::Identifier:0x0000000107c14d20 @number="8601", @part="1", @publisher="ISO", @year=2019>
irb(main):013:0> x.stage = "published"
=> "published"
irb(main):014:0> x.to_s
=> "ISO/standard 8601-1:2019"
...
irb(main):015:0> x.stage = "00.00"
=> "00.00"
irb(main):016:0> x.to_s
=> "ISO/00.00 8601-1:2019"
...
irb(main):021:0> x.stage = :PWx
=> :PWx
irb(main):022:0> x.to_s
=> "ISO/PWx 8601-1:2019"
```

1. There should be defined symbols to stages, as mentioned in https://github.com/metanorma/pubid-iso/issues/36
2. The `stage` attribute must perform validation -- it should only accept (a) mapped value as symbols, e.g. `:pwi`, `:published` (b) stage codes e.g. "20.20"
3. The generation of the identifier to string must utilize the mapping. e.g. at the `:published` stage, the output is "ISO 8601-1:2019" not "ISO/published 8601-1:2019".

**Comment by ronaldtse** [comment]
Interestingly this is implemented in pubid-iec:
https://github.com/metanorma/pubid-iec/blob/2985b8a4224899fd80cd42821be0f140c9534e59/lib/pubid/iec/renderer/urn.rb#L3-L53

**Comment by ronaldtse** [comment]
Related to this: https://github.com/metanorma/pubid-iec/issues/93

**Comment by mico** [comment]
> * The `stage` attribute must perform validation -- it should only accept (a) mapped value as symbols, e.g. `:pwi`, `:published` (b) stage codes e.g. "20.20"

How do I render stage when there are different several options available for the stage code?
E.g. (codes from pubid-ieee):
```
 ADTR: "40.99"
 ADTS: "40.99"
 AFDIS: "40.99"
 PRVD: "50.60"
 PRVDISH: "50.60"
 PRVDPAS: "50.60"
 PRVDTR: "50.60"
 PRVDTS: "50.60"
```

**Comment by ronaldtse** [comment]
@mico This is the PubID ISO gem, it does not use IEEE or IEC stages, so there is no need to discuss those in this issue.

https://github.com/metanorma/pubid-iso/issues/48#issuecomment-1209330306

| International harmonized stage code | Development stage
| -- | -- |
| 00.00, 00.20, 00.60, 00.98, 00.99 | `:pwi` |
| 10.00, 10.20, 10.60, 10.92, 10.98 | `:np` |
| 10.99 | `:awi` |
| 20.00 | `:awi` |
| 20.20, 20.60, 20.98, 20.99 | `:wd` |
| 30.00, 30.20, 30.60, 30.92, 30.98, 30.99 | `:cd` |
| 40.00, 40.20, 40.60, 40.92, 40.93, 40.98, 40.99 | `:dis` |
| 50.00, 50.20, 50.60, 50.92, 50.98, 50.99 | `:fdis` (default) or `:prf` |
| 60.00 | `:prf` |
| 60.60 | `:published` |
| 90.20, 90.60, 90.92, 90.93, 90.99 | `:published` |
| 95.20, 95.60, 95.92, 95.99  | `:published` |

NOTE: In ISO, the only conflicting stage code is 50.00 to 50.99. 

1. We need to implement a class called `HarmonizedStageCode`, it is composed of `stage_code: NN, substage_code: MM`. 
2. In `Pubid::Iso`, we need to have a class `DevelopmentStage` that contains a `HarmonizedStageCode` and the development stage (e.g. `:pwi`, `:np` ...)
3. The rendering of the `DevelopmentStage` in the output differs per document type.

**Comment by mico** [comment]
> 3\. The rendering of the `DevelopmentStage` in the output differs per document type.

How do we choose different output per document type? What is the document types?

Also don't understand why do we need separate HarmonizedStageCode class for stage codes...

**Comment by ronaldtse** [comment]
> How do we choose different output per document type? What is the document types?

Eg. DTR is the TR document type in DIS stage.  I’m confused why this is confusing. 

> Also don't understand why do we need separate HarmonizedStageCode class for stage codes...

There is a subtlety here: the stage code is a mapping to an ISO deliverable development stage. They are NOT actual stages. They only “represent” stages at certain combinations. The mapping of these codes to the IEC development stages are also different.

**Comment by mico** [comment]
> Eg. DTR is the TR document type in DIS stage. I’m confused why this is confusing.

Now after parsing "ISO/CIE DTR 21783.2" for example, output will be "ISO/CIE TR DIS 21783.2". Should we change it?

**Comment by ronaldtse** [comment]
Correct, a "TR" document at "DIS" stage is rendered with the abbreviation of "DTR".

**Comment by mico** [comment]
> There is a subtlety here: the stage code is a mapping to an ISO deliverable development stage. They are NOT actual stages. They only “represent” stages at certain combinations. The mapping of these codes to the IEC development stages are also different.

Could you give an example how it will work?
For example I have an input as `identifier = Identifier.parse("ISO FDIS 12345")`
or I can have an input as `identifier =  Identifier.new(stage: "50.00", number: 12345)`
for now the both inputs will return the same results for:
- identifier.to_s = "ISO FDIS 12345"
- identifiers.urn = "urn:iso:std:iso:12345:stage-50.00"

What will change when we implement `HarmonizedStageCode`?

**Comment by ronaldtse** [comment]
We have to remember that `#parse` is not a replacement for `#new.`

The following code should work:
```ruby
a = Identifier.new(publisher: "ISO", type: :international-standard, abbrev: "FDIS", number: 12345).to_urn
b = Identifier.new(publisher: "ISO", abbrev: "PRF", number: 12345).to_urn
c = Identifier.new(publisher: "ISO", stage: HarmonizedStageCode.new("50.00"), number: 12345).to_urn
c = Identifier.new(publisher: "ISO", stage: "50.00", number: 12345).to_urn
d = Identifier.parse("ISO FDIS 12345").to_urn
e = Identifier.parse("ISO PRF 12345").to_urn

a == b == c == d == e == f
```

What I meant for `HarmonizedStageCode` is that it accepts the `stage` and `substage` codes. Then the ISO and IEC PubIDs can use it.

```
stage_code = HarmonizedStageCode.new
stage_code.stage = "50"
stage_code.substage = "00"
stage_code.to_s
=> "50.00"
stage_code = HarmonizedStageCode.new
stage_code.stage = :approval
stage_code.substage = :registration
stage_code.to_s
=> "50.00"
stage_code.description
=> Final text received or FDIS registered for formal approval
stage_code = HarmonizedStageCode.new(stage: 90, substage: 00)
=> raise Error("90.00 is not a valid stage code.")
```
(valid values are here: https://www.iso.org/stage-codes.html)
