### ISSUE TITLE
Amd/Cor stage rendering should be kept separate from base document PubID

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-iso#51]
Now we place stage for documents with amendments/corrigendum and documents without in different places.
For "ISO/IEC 14496-12/CD Amd 4" we have stage after number, but for "ISO/IEC TR CD 20943-5" it's placed before document number.
Should we generate something like "ISO/IEC CD 14496-12/Amd 4"?
Or "ISO/IEC TR 20943-5/CD" instead of "ISO/IEC TR CD 20943-5"?

**Comment by ronaldtse** [comment]
These are two entirely different cases:

Amd/Cor uses this pattern:
```
{base PubID}/{supplement PubID}
```

* "ISO/IEC 14496-12/CD Amd 4" means CD stage of "Amd 4" for base document "ISO/IEC 14496-12".
* "ISO/IEC TR CD 20943-5" means CD stage of "ISO/IEC TR 20943-5".

The meanings are entirely different, please keep them separate. Thanks.

**Comment by mico** [comment]
> These are two entirely different cases:
> 
> Amd/Cor uses this pattern:
> 
> ```
> {base PubID}/{supplement PubID}
> ```
> 
>  * "ISO/IEC 14496-12/CD Amd 4" means CD stage of "Amd 4" for base document "ISO/IEC 14496-12".
> * "ISO/IEC TR CD 20943-5" means CD stage of "ISO/IEC TR 20943-5".
> 
> The meanings are entirely different, please keep them separate. Thanks.

How URN format should reflect it?
Now URN format don't make difference between amendment stage or document stage
```
"ISO/IEC 14496-12/CD Amd 4" -> "urn:iso:std:iso-iec:14496:-12:stage-30.00:amd:4:v1"
"ISO/IEC TR CD 20943-5" -> "urn:iso:std:iso-iec:tr:20943:-5:stage-30.00"
```

**Comment by ronaldtse** [comment]
This is a good find -- this issue is not addressed in RFC 5141.

However, we can assume the following:
* the `{base PubID}` is always the published one.

This means there is no need to encode the `stage` of the base document, and that the stage always applies to the Amd.

This is correct:
```
"ISO/IEC 14496-12/CD Amd 4" -> "urn:iso:std:iso-iec:14496:-12:stage-30.00:amd:4:v1"
"ISO/IEC TR CD 20943-5" -> "urn:iso:std:iso-iec:tr:20943:-5:stage-30.00"
```
