### ISSUE TITLE
(URGENT) Add setter method `pubid.year=` for PubID

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#60]
There is a document without a year in `hit[:title]` but we cite it by a reference with year https://github.com/relaton/relaton-iso/issues/118

However the document has a year in its metadata `hit.hit[:year]`. So in case a reference contains year, and a document has no year in `hit[:title]`, and a year from `hit.hit[:year]` match to the year in the reference we need to add year to `pubid`. Perhaps we need `pubid.year=` method.

**Comment by ronaldtse** [comment]
@mico can you please help? Thanks.

**Comment by ronaldtse** [comment]
@andrew2net can you make a PR for this? Thanks.

**Comment by andrew2net** [comment]
The parent class `Pubid::Core::Identifier` already has `#year=` method, so we don't need to implement it.
