### ISSUE TITLE
Edition and PubID

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#61]
If a document has edition number the URN should contain it. For example `urn:iso:std:iso:19115:-2:stage-60.60:ed-2`.
But if a `Pubid::Iso::Identifier` instance has `edition` attribute it also produces PubID with edition `ISO 19115-2:2019 ED2`.
I discussed it with @opoudjis and he assure me that edition shouldn't present in primary PubID identifier.
It seems we need to implement rendering PubID without edition even when edition presents.
CC @ronaldtse

**Comment by ronaldtse** [comment]
> he assure me that edition shouldn't present in primary PubID identifier.

There are supposed to be multiple types of identifiers:
- undated "ISO 19115-2"
- dated with year "ISO 19115-2:2019"
- dated with year and edition "ISO 19115-2:2019 Ed 2"
- dated with year and short lang "ISO 19115-2:2019(E)"
- dated with year and ISO 639 lang "ISO 19115-2:2019 (en)"
- dated with year and ISO 639 lang "ISO 19115-2:2019 (en) Ed 2"

@mico didn't we list out these options before? Can you add this information to the README?
