### ISSUE TITLE
Option to render language in "1-letter language code" vs "2-letter ISO 639-1 language code"

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#69]
ISO identifiers can have a language suffix under certain circumstances. I am not seeing this supported in the gem currently.

https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/front_id.rb

````
def id_langsuffix(docnum, node)
        lang = node.attr("language") || "en"
        suffix = case lang
                 when "en" then "(E)"
                 when "fr" then "(F)"
                 when "ru" then "(R)"
                 else
                   "(X)"
                 end
        "#{docnum}#{suffix}"
      end
````

So I expect to be able to pass to a "language" parameter of initialisation the ISO language codes "en", "fr", "ru", and if the parameter is present, that "(E)", "(F)", "(R)" be appended to the identifier.

**Comment by ronaldtse** [comment]
We need an option to render both `(E)` and `(en)` depending on the render option. Or we can have a global option.

As per the samples provided here:
https://github.com/metanorma/pubid-iso/issues/14

```
ISO 19109:2005(E)
ISO 14451-1:2013(en,fr,other)
ISO 17225-1:2014(R)
ISO 17225-1:2014(ru)
ISO 17301-1:2016/Amd.1:2017(F)
ISO 1891-2:2014(en,fr,ru,other)
ISO 1998-2:1976(en,fr,ru)
ISO 26000:2010(es)
ISO 31000:2009(ar)
ISO 3183:2012/DAmd 1(fr)
ISO/IEC 2382-36:2019(E/F)
ISO/IEC GUIDE 2:2004(E/F/R)
```

ISO uses these types in different scenarios:
* "single-letter language code" for within the document
* "2-letter ISO 639-1 language code" on the website

However, in the document, ISO also uses different abbreviations for the "stage + type" rendering:
* DIS stage Amd: "DAM X" in the document, "DAmd X" on the website
* FDIS stage Amd: "FDAM X" in the document, "FDAmd X" on the website
* DIS stage Cor: "DCOR X" in the document, "DCor X" on the website
* FDIS stage Cor: "FDCOR X" in the document, "FDCor X" on the website

I propose we add a rendering option `lang_format:` that accepts:
* `:single` ("E", "F", "R", "E/F", "E/F/R", etc.) or
* `:iso639` ("en", "fr", "en,fr,other", "es", etc.)

**Comment by mico** [comment]
@ronaldtse @opoudjis rendering language codes using ISO 639-1 and single code already implemented in `pubid-iso`.
You just add option for renderer if you want to render it as a single code, I added documentation for it here: https://www.rubydoc.info/gems/pubid-core/1.1.2/Pubid%2FCore%2FRenderer%2FBase:render

We also have "language" option for `Identifier` where we can supply with ISO 639-1 language code when we create new identifier, documented here: https://www.rubydoc.info/gems/pubid-core/1.1.2/Pubid%2FCore%2FIdentifier:initialize

**Comment by ronaldtse** [comment]
@mico how do I use the `with_language_code` directly using `Pubid::Iso::Identifier`? Thanks!

**Comment by mico** [comment]
> @mico how do I use the `with_language_code` directly using `Pubid::Iso::Identifier`? Thanks!

`Identifier.new(number: 123, language: "en").to_s(with_language_code: :single)` should output:

```
ISO 123 (E)
```

This was documented already, I just duplicated documentation from `Identifier#to_s` to `Renderer::Base#render`.
For some reason documentation for `Identifier#to_s` is not available at https://www.rubydoc.info/gems/pubid-iso/Pubid%2FIso%2FIdentifier:to_s
But it's published in repository https://github.com/metanorma/pubid-iso/blob/main/lib/pubid/iso/identifier.rb#L87

**Comment by ronaldtse** [comment]
Thanks! BTW, it should be "ISO 123(E)" instead of "ISO 123 (E)"?

**Comment by ronaldtse** [comment]
@opoudjis as described by @mico , can we close this now?
