### ISSUE TITLE
Generate two types of PubIDs: "Reference number" vs "PubID" (with or without language)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#7]
https://www.iso.org/obp/ui#iso:std:iso-iec:14496:-10:dis:ed-8:v1:amd:1:v1:en
https://www.iso.org/obp/ui#iso:std:iso:12164:-6:dis:ed-1:v1:fr
https://www.iso.org/obp/ui#iso:std:iso-iec:27006:ed-3:v1:ar
https://www.iso.org/obp/ui#iso:std:iso:4618:ed-2:v1:ru
https://www.iso.org/obp/ui/#iso:std:iso:14021:ed-1:v1:es

## PubID

Document cover:
<img width="489" alt="Screenshot 2022-03-07 at 12 16 23 AM" src="https://user-images.githubusercontent.com/11865/156931639-2bb8aeee-6fde-42fb-a231-3d2e4ec1e305.png">
<img width="487" alt="Screenshot 2022-03-07 at 12 20 40 AM" src="https://user-images.githubusercontent.com/11865/156931817-a6b9ecb5-5509-48be-9908-51dd0ccf6196.png">
<img width="577" alt="Screenshot 2022-03-07 at 12 39 34 AM" src="https://user-images.githubusercontent.com/11865/156932648-ec461cc6-7076-4adc-97ef-afaa5a5a6371.png">
<img width="494" alt="Screenshot 2022-03-07 at 12 28 09 AM" src="https://user-images.githubusercontent.com/11865/156932133-be53563d-bb7b-4be6-af1c-31a2a583b5a6.png">
<img width="498" alt="Screenshot 2022-03-07 at 12 29 54 AM" src="https://user-images.githubusercontent.com/11865/156932220-d87967b1-51ab-4fa1-b5ba-bceb7b5ebf67.png">

Page header:
<img width="387" alt="Screenshot 2022-03-07 at 12 16 37 AM" src="https://user-images.githubusercontent.com/11865/156931650-9d01918d-b8d8-40b4-b61d-945106188dff.png">
<img width="242" alt="Screenshot 2022-03-07 at 12 20 50 AM" src="https://user-images.githubusercontent.com/11865/156931830-6853282a-bbbf-4919-badc-55cc909e9bb4.png">
<img width="195" alt="Screenshot 2022-03-07 at 12 39 52 AM" src="https://user-images.githubusercontent.com/11865/156932663-c2e14218-5728-484c-9d78-1e70f30f9a2b.png">
<img width="177" alt="Screenshot 2022-03-07 at 12 28 15 AM" src="https://user-images.githubusercontent.com/11865/156932139-8e5050b3-f413-4106-a5c5-b6f85a63490e.png">
<img width="304" alt="Screenshot 2022-03-07 at 12 29 37 AM" src="https://user-images.githubusercontent.com/11865/156932205-03b233b0-f077-41c1-8d46-ad7b82315532.png">

## PubID with language code

<img width="648" alt="Screenshot 2022-03-07 at 12 17 36 AM" src="https://user-images.githubusercontent.com/11865/156931689-188ee139-9085-4d73-ab0e-8e622f83ce34.png">
<img width="589" alt="Screenshot 2022-03-07 at 12 21 14 AM" src="https://user-images.githubusercontent.com/11865/156931846-d2537301-9ece-40f8-a3ca-34261c536f77.png">
<img width="498" alt="Screenshot 2022-03-07 at 12 40 05 AM" src="https://user-images.githubusercontent.com/11865/156932672-068e787b-5648-4bef-bd67-866f89568cb9.png">
<img width="459" alt="Screenshot 2022-03-07 at 12 28 22 AM" src="https://user-images.githubusercontent.com/11865/156932143-f4d09aa7-b158-45c6-8b58-d4b91dc44ad0.png">
<img width="428" alt="Screenshot 2022-03-07 at 12 29 45 AM" src="https://user-images.githubusercontent.com/11865/156932212-20834fb9-1abb-47a0-8670-81f5be540d65.png">

Note that the language code is a ISO 3166 code (2-chars).

## Reference number
<img width="480" alt="Screenshot 2022-03-07 at 12 17 00 AM" src="https://user-images.githubusercontent.com/11865/156931662-12ce1571-70aa-4aca-aa1d-b5424960672e.png">
<img width="478" alt="Screenshot 2022-03-07 at 12 21 04 AM" src="https://user-images.githubusercontent.com/11865/156931840-b3f23c86-81a4-426c-abbd-3cee11f59266.png">
<img width="578" alt="Screenshot 2022-03-07 at 12 39 42 AM" src="https://user-images.githubusercontent.com/11865/156932655-0694f838-72aa-4b76-bf74-b44720fbaf14.png">
<img width="470" alt="Screenshot 2022-03-07 at 12 27 52 AM" src="https://user-images.githubusercontent.com/11865/156932122-231fd905-03de-4086-8bed-1e7d3d15ebb3.png">
<img width="470" alt="Screenshot 2022-03-07 at 12 29 19 AM" src="https://user-images.githubusercontent.com/11865/156932190-ab189baf-2b19-4147-bd16-e372b4e92f75.png">

Note that the language code is a single character:
* E for English
* F for French
* A for Arabic
* R for Russian
* There are Spanish and German translations but they don't seem to use a code. We could use S for Spanish and D for German.

**Comment by mico** [comment]
There are 2 ways how to format PubID identifier with stage:
- ISO/IEC TR 24754-2:2011
- ISO/TR 30406:2017

When we don't have copublisher we use "/" before the stage. When we have copublisher, we use a space before the stage.
@ronaldtse Should we keep this logic? I'm afraid it's not so machine readable.

**Comment by ronaldtse** [comment]
> Should we keep this logic? I'm afraid it's not so machine readable.

Yes, this is required. It is still machine-readable in our understanding because the stage acronyms (TS, TR, etc) are defined.

**Comment by mico** [comment]
"ISO/IEC 10646:2020/CD AMD 1.2"
@ronaldtse There is a stage "CD" after number, normally it's before. Is it related to amendments? Should we keep the same logic?

**Comment by ronaldtse** [comment]
Yes this is a "CD AMD", an Amendment in the "CD" stage.

**Comment by mico** [comment]
> Yes this is a "CD AMD", an Amendment in the "CD" stage.

@ronaldtse I cannot see how is it implemented for URN, no mention there that stage could belong to Amendment or Corrigendum

**Comment by mico** [comment]
> https://www.iso.org/obp/ui#iso:std:iso-iec:14496:-10:dis:ed-8:v1:amd:1:v1:en https://www.iso.org/obp/ui#iso:std:iso:12164:-6:dis:ed-1:v1:fr https://www.iso.org/obp/ui#iso:std:iso-iec:27006:ed-3:v1:ar https://www.iso.org/obp/ui#iso:std:iso:4618:ed-2:v1:ru https://www.iso.org/obp/ui/#iso:std:iso:14021:ed-1:v1:es

Seems these are URN identifiers. They differ from what we generate. Stage here is just a short code, not numeric. Amendment without year has number "1" before version. Edition has a version (ed-2:v1). Should we consider this?

**Comment by ronaldtse** [comment]
> Amendment without year has number "1" before version. Edition has a version (ed-2:v1).

Yes we should do this.

RFC 5141 also has version for edition:
```
   o  Docversion handling:

      urn:iso:std:iso:9999:-1:ed-1:v2:en
      refers to the corrected English version of the 1st edition of ISO
      9999-1

      urn:iso:std:iso:9999:-1:ed-1:v1-amd1:en
      refers to the version comprising the 1st edition of ISO 9999-1,
      incorporating the latest version of Amendment 1, in English

      urn:iso:std:iso:9999:-1:ed-1:v1:en,fr:amd:1:v2:en
      refers to the 2nd version of Amendment 1, in English, which amends
      the 1st version of edition 1 of ISO 9999-1, in English/French
      (bilingual document)

      urn:iso:std:iso:9999:-1:ed-1:v1-amd1.v1:en,fr:amd:2:v2:en
      (isoversion scheme)
      refers to the corrected version of Amendment 2, in English, which
      amends the document comprising the 1st version of edition 1 of ISO
      9999-1 incorporating the 1st version of Amendment 1, in English/
      French (bilingual document)

      urn:iso:std:iso:5817:ed-2:v2:en:cor:1:en
      refers to the 1st version of Technical Corrigendum 1, in English,
      which amends the corrected version of edition 2 of ISO 5817, in
      English

```

It describes `docversion`:

```
   docversion    = "v" (simpleversion / isoversion)

   simpleversion = DIGITS

      <docversion> designates the version number of a document's
      <edition>.  It is altered by correction (corrected version;
      Technical Corrigendum) or amendment (Amendment; Addendum) and is
      distinct from a revision, which changes the edition number.

      In the <simpleversion>, the first version published is 1, and each
      subsequent correction or amendment increases the version number by
      1.

      If no <docversion> is specified, the reference is to the highest
      version number available for the denoted <edition>.

      Current values of <simpleversion>:

         1 - first version published

         2 - corrected version published

   isoversion    = baseversion *includedsuppl

   baseversion   = DIGITS
```

> Stage here is just a short code, not numeric

We should consider this indeed. In RFC 5141, only this is allowed:

```
   status        = ( "draft" / "cancelled" ) / stage

      <status> indicates the publication status of the document.  When
      the <status> element is not present, the NSS refers to a published
      document.  Other values:

      draft     = document that has not yet been accepted for
                  publication by international ballot

      cancelled = document that has been deleted or withdrawn
```

Let me contact ISO about this.

**Comment by mico** [comment]
@ronaldtse In the title you mention we should "Generate two types of PubIDs". Couldn't get what is another type. Reference number and PubID look the same. Did I cover everything in #18, what is missing?

**Comment by ronaldtse** [comment]
@mico Maybe I used the wrong mechanism to distinguish the features. Notice that there are two differences:

1. Dated vs undated. "ISO 9001:2005" vs "ISO 9001".
2. Language code: absent vs 1-character vs 2-character.

These should probably be options when generating the PubID?

e.g.
```ruby
mypubid = Pubid::Iso::Identifier.new("ISO 9001:2005(E)")
mypubid.to_s => "ISO 9001:2005(E)"
mypubid.to_s(dated: true) => "ISO 9001:2005"
mypubid.to_s(dated: false) => "ISO 9001"
mypubid.to_s(lang: :iso) => "ISO 9001:2005(en)"
mypubid.to_s(lang: :single) => "ISO 9001:2005(E)"
```

**Comment by mico** [comment]
> https://www.iso.org/obp/ui#iso:std:iso-iec:14496:-10:dis:ed-8:v1:amd:1:v1:en

@ronaldtse how about "amd:1:v1" here? It's PubID "ISO/IEC 14496-10:2014/DAM 1" now we use only "amd:v1" without "1" between for this. Should I add "1" between there? I don't understand exactly what it means there, because we have version there already. Maybe number "1" is default when the year is missing...

**Comment by ronaldtse** [comment]
@mico "amd:1" is the "first" amendment. "v1" is the default version unless it was corrected. So "amd:1:v1" is correct.

From RFC 5141:
```
      urn:iso:std:iso:9999:-1:ed-1:v1:en,fr:amd:1:v2:en
      refers to the 2nd version of Amendment 1, in English, which amends
      the 1st version of edition 1 of ISO 9999-1, in English/French
      (bilingual document)
```
