### ISSUE TITLE
Provide generator usable by metanorma-iso

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-iso#70]
The constructor with documentation provided remains inadequate for the needs of metanorma-iso. I cannot work out how to generate the identifiers I need to, and I do not have the time to reimplement them. I need this gem to generate identifiers given the information I provide.

So, I will provide the following information. I require you to provide me with code to convert that into the constructor you expect, or else implement fields to deal with them. I have no desire to hunt down the definition of Pubid::Core::Supplement, to work out how to create Corrigenda. It is your responsibility to convey to me as a user how to do so.

The parameters I can supply are:

````
number
part: I DO NOT SEE WHERE TO PROVIDE THIS
amendment_number: YOU NEED TO PROVIDE THE CODE FOR HOW TO GENERATE THIS
corrigendum_number: DITTO
language: I DO NOT SEE WHERE TO PROVIDE THIS
urn_stage
stage: I HAVE ALREADY ARGUED I SHOULD NOT BE REQUIRED TO LOOK THIS UP OUTSIDE OF THIS GEM
type: I DO NOT SEE WHERE TO PROVIDE THIS. The gem seems to only support DIR and not TR TS in class initialisation. That makes it unusable
year: I DO NOT SEE WHERE TO PROVIDE THIS
copublisher: for joint publications
````

**Comment by ronaldtse** [comment]
@mico this is urgent, please help @opoudjis out here.

**Comment by mico** [comment]
@opoudjis could you check https://www.rubydoc.info/gems/pubid-core/1.0.1/Pubid/Core/Identifier#initialize-instance_method
`pubid-iso` inherit methods from `pubid-core`
Do you still have questions or requirement to change something after seeing that?

**Comment by ronaldtse** [comment]
Thanks @mico, the documentation in pubid-core is fine. The current implementation, however, needs to be fixed as per https://github.com/metanorma/pubid-iso/issues/48#issuecomment-1221752393 .

**Comment by opoudjis** [comment]
The documentation is false about Amendments:

https://www.rubydoc.info/gems/pubid-core/1.0.1/Pubid/Core/Identifier#initialize-instance_method

````
amendments (Array<[Amendment](https://www.rubydoc.info/gems/pubid-core/1.0.1/Pubid/Core/Amendment)>) (defaults to: nil) — document's amendments
````

I would assume from that that amendments is intialised as:

Pubid::Iso::Identifier.new(amendments: Pubid::Iso::Amendement.new(number: "2"))

In fact, the code has:

````
def initialize(amendments: nil, corrigendums: nil, **opts)
      if amendments
        @amendments = if amendments.is_a?(Array)
                        amendments.map do |amendment|
                          self.class.get_amendment_class.new(**amendment)
                        end
                      else
                        [self.class.get_amendment_class.new(**amendments)]
                      end
      end
````

which means the correct initialisation is:

````
Pubid::Iso::Identifier.new(amendments: { number: "2" })
````

The documentation simply cannot be used if it is going to be misleading like this. If an argument is going to be a hash, it needs to be documented as a hash, not as the class being initialised as the hash.

**Comment by opoudjis** [comment]
You also don't say what the difference is between the two arguments of "copublisher", if any.

**Comment by mico** [comment]
> Pubid::Iso::Identifier.new(amendments: Pubid::Iso::Amendement.new(number: "2"))

Correct ininialization will be:
`Pubid::Iso::Identifier.new(amendments: [Pubid::Iso::Amendement.new(number: "2")])`

> In fact, the code has:

It's outdated code, we don't have it anymore.

**Comment by ronaldtse** [comment]
This issue is likely outdated. Closing.
