### ISSUE TITLE
Support parsing "ISO 8601-1:2019/FDAM 1:2022(E)" identifier

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#71]
It is rather strange that ISO uses both "FDAM 1" and "FDAmd 1" abbreviations. 

The project page uses "FDAmd 1":
<img width="550" alt="Screen Shot 2022-08-15 at 2 09 04 AM" src="https://user-images.githubusercontent.com/11865/184549479-6382d47d-90fc-4209-91ac-4cf48997e4e7.png">

The filename is also "FDAmd 1":
<img width="315" alt="Screen Shot 2022-08-15 at 2 09 20 AM" src="https://user-images.githubusercontent.com/11865/184549487-98919e38-1050-4649-af74-1d917b056bc7.png">

But the document uses "FDAM 1".

We probably should distinguish this as one more ISO identifier rendering option (choosing between "FDAmd" and "FDAM"; "DAmd" and "DAM").

PubIDs to parse and generate:
* ISO 8601-1:2019/FDAM 1:2022(E)
* ISO 8601-1:2019/FDAM 1:2022
* ISO 8601-1:2019/FDAM 1
* ISO 8601-1:2019/DAM 1:2022(E)
* ISO 8601-1:2019/DAM 1:2022
* ISO 8601-1:2019/DAM 1

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/758#issuecomment-1214425102_

**Comment by mico** [comment]
@ronaldtse now output after parsing "ISO 8601-1:2019/FDAM 1:2022(E)" (or FDAmd) become:

> ISO 8601-1:2019/FDIS Amd 1:2022(en)

And for "ISO 8601-1:2019/DAM 1:2022(E)" (or DAmd) it become:

> ISO 8601-1:2019/DIS Amd 1:2022(en)

Is it wrong?
Do we want to add options to render it as "FDAM" and "DAM"  or "FDAmd" and "DAmd" instead of full form ("FDIS Amd" and "DIS Amd")?

**Comment by ronaldtse** [comment]
"ISO 8601-1:2019/FDIS Amd 1:2022(en)" and "ISO 8601-1:2019/DIS Amd 1:2022(en)" are incorrect. We should not generate them. 

We need to have allow generating the following two types of identifiers, differentiated by option.

DIS Amd:
* "ISO 8601-1:2019/DAM 1:2022(E)"
* "ISO 8601-1:2019/DAmd 1:2022(E)"

FDIS Amd:
* "ISO 8601-1:2019/FDAM 1:2022(E)"
* "ISO 8601-1:2019/FDAmd 1:2022(E)"

**Comment by ronaldtse** [comment]
This task is expanded in #77 .

**Comment by mico** [comment]
This was fixed in #77
