### ISSUE TITLE
Handling non-standard "pre{STAGE}" identifiers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#76]
As per https://github.com/metanorma/metanorma-iso/issues/16

Occasionally ISO TCs will issue identifiers like this:
```
ISO/IEC preCD 29134
```

The current implementation in Metanorma is:
* https://github.com/metanorma/metanorma-iso/commit/fc8d291fc8db0bc7ff001bf80aca7029599e7a9a
* https://github.com/metanorma/metanorma-iso/commit/7abef956b1a06dd1da42066b0b5f9dc94a65c7cf

We need to decide how to handle this, e.g.
* "ISO/IEC preCD 29135" => "ISO/IEC preCD 29135" (mark as `draft: true, stage: "CD"`) or
* "ISO/IEC preCD 29135" => "ISO/IEC CD.0 29135" (`stage: "CD", iteration: 0`)

**Comment by ronaldtse** [comment]
It seems that "preCD" is a common IEC stage.

**Comment by mico** [comment]
@ronaldtse in the description [here](https://github.com/metanorma/metanorma-iso/commit/fc8d291fc8db0bc7ff001bf80aca7029599e7a9a#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R332) "draft" format is "X.Y" and in the test asset [here](https://github.com/metanorma/metanorma-iso/blob/main/spec/assets/iso.xml#L21) draft is the number "0.4".
Should we follow the same pattern, and how does this numbers affects rendered PubID and URN?

**Comment by ronaldtse** [comment]
@mico in the future, we may have an iteration that acts like a version number, i.e. major.minor.

In any case, the test [here](https://github.com/metanorma/metanorma-iso/blob/main/spec/assets/iso.xml#L21) does not make sense because it is PreCD3 but has draft version 0.4.

**Comment by mico** [comment]
@ronaldtse reading the comments I cannot figure out what we decided to do.
`PreCD3` is draft version 0.4, so what is number "3" here?
Is `preCD` draft version 0?

**Comment by ronaldtse** [comment]
I don’t have an answer. We should do what IEC does here.

**Comment by mico** [comment]
> I don’t have an answer. We should do what IEC does here.

@ronaldtse What I found about what IEC does with "preCD", is only "preCD" comes before "CD".
So it's another stage before CD
But I didn't find any "preCD" with numbers, like "preCD3".
I can just store "3" as some kind of stage number, without associating it with iteration.

**Comment by mico** [comment]
@ronaldtse I'm trying to check if `ISO/PreCD3 17301-1` is really exist.
How can we check if `PreCD3` is existing stage?

**Comment by opoudjis** [comment]
@mico you have just asked me this question.

https://www.metanorma.org/author/iec/ref/document-attributes/ explictly says we are currently ignoring preCD. And the lack of any harmonised stage equivalent is the reason why.

It is clear that the international harmonised stages are not truly applicable to IEC, and have only been designed for the simpler (and far clearer) ISO process.

I do not know any more than you do about this question, and the preCD stage is not documented in the authoritative IEC documentation at all ( https://www.iec.ch/system/files/2023-05/Consolidated_ISO-IEC_Part-1_IECSupplement_2023_redline.pdf https://www.iec.ch/standards-development/stages ) . I am going to just make an answer up, and you are just as capable of making an answer up as I am.

@ronaldtse is saying that he wants preCD treated as a separate stage. The stages are not actually used by IEC, so we are at liberty to assign our own intermediate numbers. There is precedent of intermediate numbers in substages (92, 93, 98, 99) and in stages (95): https://www.iso.org/stage-codes.html

.... So if we want a new stage between 20 and 30, and we are free to make up a stage number (which, in the absence of any guidance from IEC, we are), then use 29.

What's the alternative, after all? If we use either 20 or 30, then we are not deviating from ISO stages, but we are also not capturing PreCD as a distinct stage. Use 29, and if it blows up for whatever reason, we'll revisit the decision.
