### ISSUE TITLE
Pre-defined option (`to_s(...)`) of rendering document identifier vs website 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#77]
The document identifiers used on the ISO website, vs those used in the document, are different.

Example: ISO 8601-1:2019/DAmd 1

The website uses “ISO 8601-1:2019/DAmd 1(en)"
[ISO OBP](https://www.iso.org/obp/ui/#iso:std:iso:8601:-1:dis:ed-1:v1:amd:1:v1:en)
<img width="629" alt="Screen Shot 2022-08-28 at 12 11 51 PM" src="https://user-images.githubusercontent.com/11865/187101291-f04a6220-8cdc-41fd-9ee9-8feb4ffcdfc7.png">

The document uses “ISO 8601-1:2019/DAM 1"
https://github.com/CalConnect/iso-8601-1-amd1/tree/main/submission/20210727-damd-proof
<img width="1134" alt="Screen Shot 2022-08-28 at 12 18 14 PM" src="https://user-images.githubusercontent.com/11865/187101299-373595fd-9187-4ec2-9451-a9e2470f84e2.png">

The document states the “Reference number” as “ISO 8601-1:2019/DAM 1:2021(E)”.
<img width="343" alt="Screen Shot 2022-08-28 at 12 18 50 PM" src="https://user-images.githubusercontent.com/11865/187101335-0eab9f0c-239f-473b-afd1-3f9c7ed1ee10.png">

Similarly, for FDIS:

Website for undated:
https://sd.iso.org/projects/project/81801/overview
<img width="538" alt="Screen Shot 2022-08-28 at 12 20 06 PM" src="https://user-images.githubusercontent.com/11865/187101350-43dbd33d-ab33-439f-8d9c-3245d5e76d62.png">

Document for undated:
https://github.com/CalConnect/iso-8601-1-amd1/tree/main/submission/20220726-fdam-proof
<img width="669" alt="Screen Shot 2022-08-28 at 12 20 17 PM" src="https://user-images.githubusercontent.com/11865/187101384-72fbb862-23c4-4413-989a-36a05d2ea90c.png">

Document for dated:
<img width="220" alt="Screen Shot 2022-08-28 at 12 20 33 PM" src="https://user-images.githubusercontent.com/11865/187101403-c6edba24-6dd1-4e67-8723-388a58c9b9f0.png">

It seems that there are at least 4 types of identifiers here:

1. Website undated, no language: ISO 8601-1:2019/DAmd 1 (seen on the ISO Projects site)
2. Website dated, with language: ISO 8601-1:2019/DAmd 1:2021(en) (seen on the ISO OBP)
3. Document undated, no language: ISO 8601-1:2019/DAM 1 (document cover top)
4. Document dated, with language: ISO 8601-1:2019/DAM 1:2021(E) (document cover bottom, header and footer)

And in the bibliographic references, these are used:
5. Document undated, without language: ISO 8601-1:2019/DAM 1
6. Document dated, without language: ISO 8601-1:2019/DAM 1:2021

i.e.
* "Undated" identifiers seem to never have language
* "Dated" identifiers can clearly have language (as in the document reference) and no language.

This means that we need to have these options for rendering:
* "no language code" vs "1 letter code" vs "2 letter code" #69 
* Short form vs long form "stage+type": DAM vs DAmd (this ticket)
* Dated vs undated: whether there is edition year rendered
* "edition" is always not rendered

We can conclude that we need the following types of predefined formats:
* instance reference number: 1 letter language code + short form (DAM) + dated
* instance reference number long: 2 letter language code + long form (DAmd) + dated
* reference dated: no language code + short form (DAM) + dated
* reference dated long: no language code + short form (DAM) + dated
* reference undated: no language code + short form (DAM) + undated
* reference undated long: 1 letter language code + long form (DAmd) + undated

One way to realize these predefined formats are:
```ruby
> pubid = Pubid::Iso::Identifier.new(
  number: "8601", 
  part: "1", 
  year: 2019, 
  edition: 1, 
  amendment: {number: "1", year: "2021", stage: "DIS"}
)
> pubid.to_s(:ref_num_short)
=> "ISO 8601-1:2019/DAM 1:2021(E)"
> pubid.to_s(:ref_num_long)
=> "ISO 8601-1:2019/DAmd 1:2021(en)"
> pubid.to_s(:ref_dated)
=> "ISO 8601-1:2019/DAM 1:2021"
> pubid.to_s(:ref_dated_long)
=> "ISO 8601-1:2019/DAmd 1:2021"
> pubid.to_s(:ref_undated)
=> "ISO 8601-1:2019/DAM 1"
> pubid.to_s(:ref_undated_long)
=> "ISO 8601-1:2019/DAmd 1"
```

**Comment by mico** [comment]
@ronaldtse do we have similar pattern (stage+type) for Corrigendum? Cannot find any examples or tasks related to this?

**Comment by ronaldtse** [comment]
@mico yes, the pattern for Amendment and Corrigendum is similar:

DCor (long) => DCOR (short)
FDCor (long) => FDCOR (short)

ISO/IEC 14496-12 DCOR 1
ISO/IEC 19757-4 DCOR
ISO/TR 23455:2019/FDCor 1

**Comment by mico** [comment]
@ronaldtse I found another patterns for "CD" stage:
- ISO/IEC 10646-1:1993/pDCOR.2
- ISO/IEC 14496-12/PDAM 4

Now we converting it to long versions:

- ISO/IEC 10646-1:1993/CD Cor 2
- ISO/IEC 14496-12/CD Amd 4

Also I found there are documents with "FPDAM" (Final Proposed Draft Amendment).

Should we do something about these patterns?

**Comment by ronaldtse** [comment]
@mico thank you for raising this.

## "PDAM" and "FPDAM"

These are valid but outdated abbreviations:
* "PDAM"
* "FPDAM"
* "PDTS"
* "PDTR"

As per this page (https://www.unicode.org/faq/alpha_soup.html) , "PDAM" and "FPDAM" are no longer in use:
> PDAM. Proposed Draft Amendment. (A document ballot category no longer in use. See CDAM.)
> FPDAM. Final Proposed Draft Amendment. (A document ballot category no longer in use.)

ISO did still use them in 2019:
<img width="796" alt="Screen Shot 2022-09-13 at 3 56 54 PM" src="https://user-images.githubusercontent.com/11865/189844347-c29ca465-361f-4897-90a0-b956f8fed673.png">

And they are found on the ISO website:
* ISO/IEC 23008-3:2015/FPDAM 1(en)
* ISO/IEC 19794-5:2011/FPDAM 2(en)

The second document is at:
* https://www.iso.org/obp/ui#iso:std:iso-iec:19794:-5:dis:ed-2:v1:amd:2:v1:en

Notice that the code is DIS stage, and uses "DAM 2" instead of "FPDAM 2".

<img width="1188" alt="Screen Shot 2022-09-13 at 4 00 33 PM" src="https://user-images.githubusercontent.com/11865/189845190-ada21be6-8cf7-4448-945e-aa4a5e016f68.png">

So I think we can map:
* FPDAM (and "FP" prefix) to "DIS" stage
* PDAM (and "P" prefix) to "CD" stage

And we will have to retain these document identifiers. 

## CDAM

In addition, it seems that ISO/IEC JTC 1 is still using the "CDAM" identifier now in 2022:
* ISO/IEC 14496-12:2021 CDAM 1 

<img width="633" alt="Screen Shot 2022-09-13 at 4 07 20 PM" src="https://user-images.githubusercontent.com/11865/189846645-a7259060-aa80-44e2-830c-ed64a1b8b537.png">
<img width="616" alt="Screen Shot 2022-09-13 at 4 07 45 PM" src="https://user-images.githubusercontent.com/11865/189846740-9147a0e2-3007-48b9-95a8-bb1d48134133.png">

So we should support it.

"CD Amd" (long) => "CDAM" (short)

**Comment by mico** [comment]
> ```ruby
> > pubid.to_s(:ref_num_short)
> => "ISO 8601-1:2019/DAM 1:2021(E)"
> > pubid.to_s(:ref_num_long)
> => "ISO 8601-1:2019/DAmd 1:2021(en)"
> > pubid.to_s(:ref_dated)
> => "ISO 8601-1:2019/DAM 1:2021"
> > pubid.to_s(:ref_dated_long)
> => "ISO 8601-1:2019/DAmd 1:2021"
> > pubid.to_s(:ref_undated)
> => "ISO 8601-1:2019/DAM 1"
> > pubid.to_s(:ref_undated_long)
> => "ISO 8601-1:2019/DAmd 1"
> ```

Should I add language code only for the cases when language code was in the source (when parsing) or was added while creating identifier only? (Current behavious)
Or I should always add default language code (english) except cases when format without language was requested? (does it affect all identifiers? I mean others beside identifiers with supplements)

**Comment by ronaldtse** [comment]
I think we should make the language code an option in rendering.

> Should I add language code only for the cases when language code was in the source (when parsing) 

Yes. When parsing, if there is a language code, we should also show it when the object is rendered.

**Comment by mico** [comment]
> ```ruby
> > pubid.to_s(:ref_undated_long)
> => "ISO 8601-1:2019/DAmd 1"
> ```

@ronaldtse we already have option to remove date from identifier, for example "ISO 8601-1:2019" become "ISO 8601-1".
But in this example (`ISO 8601-1:2019/DAmd 1:2021`), we also have amendment date. Should we remove both document published date and amendment date? Or should we have an option to remove only amendment date?
Format option "ref_undated_long" don't mention it's related to supplement only.

**Comment by ronaldtse** [comment]
> Should we remove both document published date and amendment date?

We need to clarify how the edition year (the date) applies:
* In "ISO 8601-1:2019", the edition year is "2019". With 2019, it is an exact reference (i.e. can find the document). Without 2019, it is an "undated reference" (i.e. it applies to ISO 8601-1:2019, ISO 8601-1:20xx, etc).
* In "ISO 8601-1:2019/DAmd 1:2021", there is only one edition year, which is "2021". The "2019" part belongs to the base document, and cannot be removed.
  * The reason is an Amendment (or Corrigendum) is a document that "applies" on top of another document, it can only exist if the base document is an exact reference. For example, if the base document is an undated reference, e.g. "ISO 8601-1/DAmd 1", the base document represents a series (ISO 8601-1:2019, ISO 8601-1:20xx...) which cannot be a base for the Amendment.

Therefore, the dated vs undated identifiers are as follows:
* Normal PubID: "ISO 8601-1" (undated), "ISO 8601-1:2019" (dated)
* Supplement PubID: "ISO 8601-1:2019/Amd 1" (undated), "ISO 8601-1:2019/Amd 1:2021" (dated)
