### ISSUE TITLE
Internationalized PubIDs: Russian

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#8]
ISO provides PubIDs in Russian:

* ISO is ИСО
* ISO/IEC is ИСО/МЭК
* TR is ТО
* TS is ТС
* DIS is ПМС
* FDIS is ОПМС
* "ISO Guide" is "Руководства ИСО"
* "ISO/IEC Guide" is "Руководство ИСО/МЭК"

NOTE: More information can be found here: https://ru.delta-engineering.be/iso

All the following identifiers come from official ISO information, mostly from the website.
```
ИСО 10335
ИСО 1126
ИСО 124
ИСО 127
ИСО 1304
ИСО 1431-1
ИСО 1435
ИСО 15105
ИСО 18064
ИСО 2321
ИСО 289-1
ИСО 289-2
ИСО 289-3
ИСО 2930
ИСО 35
ИСО 37001
ИСО 3858
ИСО 4223-1
ИСО 4223-2
ИСО 45000
ИСО 4649
ИСО 4660
ИСО 472
ИСО 48
ИСО 506
ИСО 5435
ИСО 6107-6
ИСО 6107-6:1996
ИСО 6194-2
ИСО 8330
ИСО 8511
ИСО 8942
ИСО 9001:2015
ИСО 9026
ИСО/МЭК 76:2008
ИСО/МЭК ТО 19791:2008 # This is ISO/IEC
ИСО/ОПМС 26000:2010(R) # ОПМС is FDIS
ИСО/ОПМС 9000:2000
ИСО/ПМС 1956/2 # ПМС is DIS
ИСО/ТК
ИСО/ТО 8517 # This means ISO/TR 8517
ИСО/ТС 18625 # This means ISO/TS 18625
Руководства ИСО 2
Руководства ИСО 82
Руководство ИСО/МЭК 76
```

**Comment by mico** [comment]
@ronaldtse do we want to produce Russian version of PubIDs, like French version?

**Comment by ronaldtse** [comment]
@mico absolutely. ISO has 3 official languages: English, French and Russian. PubIDs are created in these languages differently. They also have the Arabic language PubID format, even though that is not officially used.

**Comment by ronaldtse** [comment]
Since ISO Russian standards are published less common than English/French, I am not able to find the acronyms of the stages (e.g. Russian version of AWI, WD) and document types (e.g. IWA in Russian)

**Comment by mico** [comment]
> Since ISO Russian standards are published less common than English/French, I am not able to find the acronyms of the stages (e.g. Russian version of AWI, WD) and document types (e.g. IWA in Russian)

I found it there: https://ru.delta-engineering.be/iso
<img width="882" alt="image" src="https://user-images.githubusercontent.com/5849/157448642-cbc94c6a-f4db-4913-9ae4-b1ee3b0372d8.png">
AWI == АВИ
CD == КПК (need to double check)
ПДТР == PDTR
ПДТС == PDTS
and more on the page

**Comment by ronaldtse** [comment]
That's why I gave that link 😉 Thanks!

**Comment by mico** [comment]
> I found it there: https://ru.delta-engineering.be/iso <img alt="image" width="882" src="https://user-images.githubusercontent.com/5849/157448642-cbc94c6a-f4db-4913-9ae4-b1ee3b0372d8.png">

@ronaldtse Information is quite messy there, it's hard for me to understand what equal what, for example for stage 40 we have a list of stage identifiers:

- DIS
- FCD
- FPDAmd
- ДАмд (ДАМ)
- ФПДИСП
- DTR
- DTS

ok, "ДАмд" is transliteration of "DAmd", but "ФПДИСП" in transliteration should be "FPDISP", so maybe it's FPD stage and ISP type...
Only stages covered on the page, no types or organizations in Russian. No "corrigendum" in Russian. If we would have more examples for Russian PubIDs, maybe we could extract more information.

**Comment by ronaldtse** [comment]
> "ФПДИСП" in transliteration should be "FPDISP", so maybe it's FPD stage and ISP type...

That's probably correct.

Let's just do whatever you have for now. We can get clarification in the future.
