### ISSUE TITLE
Amendment/Corrigendum number cannot be rendered with a colon

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#80]
```ruby
irb(main):011:0> Pubid::Iso::Identifier.new(number: 17301, part: 1, publisher: "ISO", language: "en", year: 2016, amendments: [{number: 1, stage: "NP"}]).to_s
=> "ISO 17301-1:2016/NP Amd :1(en)"
```

The output is wrong, it should be: "ISO 17301-1:2016/NP Amd 1(en)"

**Comment by mico** [comment]
@ronaldtse is it ok that PubID with edition year don't have edition year in generated URN?
`ISO 19110:2005/Amd 1:2011` -> `urn:iso:std:iso:19110:amd:2011:v1`
That's how it works now.

Not sure to which task leave this comment.
