### ISSUE TITLE
PubID with edition year don't have edition year in generated URN

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#95]
From @mico:

PubID with edition year don't have edition year in generated URN:
`ISO 19110:2005/Amd 1:2011` -> `urn:iso:std:iso:19110:amd:2011:v1`

That's how it works now.

_Originally posted by @mico in https://github.com/metanorma/pubid-iso/issues/80#issuecomment-1248235498_

**Comment by ronaldtse** [comment]
RFC 5141, which documents the ISO URN scheme, indeed does not support encoding of the year:
https://www.rfc-editor.org/rfc/rfc5141.html

This means we can only generate the URN properly if we have the edition number.

We just need to be sure that the user has a way to enter the edition number for the base document, to generate the correct URN.

**Comment by mico** [comment]
I believe it was fixed here https://github.com/metanorma/pubid-iso/pull/111
