### ISSUE TITLE
Support PAS, CD PAS, and DPAS pubids

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#96]
We need to add tests for:

* PAS in WD stage => WD PAS
* PAS in CD stage => CD PAS
* PAS in DIS stage => DPAS
* PAS in IS stage => PAS
* Also, we need to prohibit FDIS stage for PAS type by raising an error.

```
ISO/DPAS 5643:2021(E)
ISO/PAS 5643:2021
ISO/PRF PAS 5643
ISO/PRF PAS 5643:2021
ISO/DPAS 50010
ISO/PAS 5112:2022
ISO/DPAS 22101-1.5   (this means DIS iteration 5)
ISO/PAS 22101-1:2022
ISO/SAE DPAS 22736:2021
ISO/SAE PAS 22736:2021
ISO/SAE PRF PAS 22736
ISO/CD PAS 50010 
ISO/CD PAS 24019
ISO/CD PAS 22399
```

**Comment by mico** [comment]
@ronaldtse Shouldn't "ISO/CD PAS 22399" be rendered as "ISO/PAS/CD 22399"? See requirements in #105

**Comment by ronaldtse** [comment]
@mico No, the non-IS document type ("PAS") never has a trailing slash ("PAS/CD" is invalid). "ISO/CD PAS 22399" is correct.

**Comment by ronaldtse** [comment]
The correct patterns are:
* "{multiple-publishers} {stage + doctype}"
* "ISO/{stage + doctype}"

There is no contradiction with #105.

**Comment by mico** [comment]
> @mico No, the non-IS document type ("PAS") never has a trailing slash ("PAS/CD" is invalid). "ISO/CD PAS 22399" is correct.

But we have ISO/TR identifiers like "ISO/TR 12134:2010" - should it look something like ""ISO/WD TR 12134:2010" if stage applied?

**Comment by ronaldtse** [comment]
@mico yes you're correct, "ISO/WD TR 12134:2010" is accurate.

**Comment by mico** [comment]
@ronaldtse we don't include "IS" for supplements and "PAS" documents. Is there any other documents for which we exclude "IS" from output?

**Comment by ronaldtse** [comment]
@mico Only "IS" is omitted from all PubIDs. Supplements will always have the full base PubID. PAS documents are just like TR and TS.
