### ISSUE TITLE
Setting a default format for to_s

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-iso#98]
As done in #77, there are 6 pre-defined string formats for an ISO PubID:

```ruby
> pubid.to_s(:ref_num_short)
=> "ISO 8601-1:2019/DAM 1:2021(E)"
> pubid.to_s(:ref_num_long)
=> "ISO 8601-1:2019/DAmd 1:2021(en)"
> pubid.to_s(:ref_dated)
=> "ISO 8601-1:2019/DAM 1:2021"
> pubid.to_s(:ref_dated_long)
=> "ISO 8601-1:2019/DAmd 1:2021"
> pubid.to_s(:ref_undated)
=> "ISO 8601-1:2019/DAM 1"
> pubid.to_s(:ref_undated_long)
=> "ISO 8601-1:2019/DAmd 1"
```

Now we need to set a default format.

**Comment by ronaldtse** [comment]
## Argument for `ref_num_long`

Short: "ISO 8601-1:2019/DAM 1" can't be found on iso.org
![image](https://user-images.githubusercontent.com/11865/190573662-6f6f19bf-f692-41ec-8cd8-bf58f16bb3c8.png)

Long: "ISO 8601-1:2019/DAmd 1" can be found on iso.org
![image](https://user-images.githubusercontent.com/11865/190573693-2c32a73b-dd58-490c-8972-302d2205dfa5.png)

**Comment by ronaldtse** [comment]
Let's use `ref_dated_long` as the default of `to_s` for now. Thanks!

**Comment by opoudjis** [comment]
@ronaldtse 

Once again, I am being left out of the loop, and that is wreaking havoc on my testing. 

Until now, I was generating the iso-reference identifier as

ISO 8601-1:2019/DAmd 1:2021(E)

I have no idea what I am meant to put in there now, so I'm just going to guess that it's going to be

"ISO 8601-1:2019/DAmd 1:2021(en)"
